- ios/Classes/AudioplayerPlugin.m
> Fix: seek not working on ios

- android/build.gradle
- android/src/main/java/bz/rxla/audioplayer/AudioplayerPlugin.java
- example/android/app/build.gradle
- example/android/build.gradle
- example/android/settings.gradle
- example/ios/Flutter/Debug.xcconfig
- example/ios/Flutter/Release.xcconfig
- example/lib/main.dart
I did some refactorings and fix the "frees UI on Android" problem
> #7 audio player blocks ui on andorid

- android/src/main/java/xyz/luan/audioplayers/WrappedMediaPlayer.java
Add fallbacks in order to (really) support SDKs 16-20.
> Support Android SDK 16-20

- analysis_options.yaml
- example/lib/player_widget.dart
- lib/audioplayers.dart
- pubspec.lock
> Adding player state

- android/src/main/java/xyz/luan/audioplayers/AudioplayersPlugin.java
- example/lib/main.dart
- example/lib/player_widget.dart
- ios/Classes/AudioplayersPlugin.m
- lib/audioplayers.dart
> Fix playing external links.

- pubspec.lock
- pubspec.yaml
Hi, this should close #108 
I've put on a separate commit the update to `pubspec.lock` as I'm not sure you want to merge it (I'm usually on the flutter master branch, therefore a bit ahead). I can revert that commit, in case.
Thanks for having a look at my PR! And thanks for making my life easier :-) with your library :+1:
> Update path_provider library dependency

- pubspec.lock
- pubspec.yaml
> Updated uuid dependency to v2.0.0

- .gitignore
- README.md
- android/src/main/java/xyz/luan/audioplayers/AudioplayersPlugin.java
- android/src/main/java/xyz/luan/audioplayers/Player.java
- android/src/main/java/xyz/luan/audioplayers/WrappedMediaPlayer.java
- android/src/main/java/xyz/luan/audioplayers/WrappedSoundPool.java
- example/lib/main.dart
- example/lib/player_widget.dart
- lib/audio_cache.dart
- lib/audioplayers.dart
This only affects Android.
This is a new `audioplayers` backend based on SoundPool to reduce impacts on visuals or UI performance.
Note that some features of the `AudioPlayer` API won't work with this mode.
Comments and feedbacks are welcome :)
> Low Latency API

- README.md
Update position event documentation.
Add `onPlayerStateChanged` event documentation.
> Update Streams documentation.

- android/src/main/java/xyz/luan/audioplayers/WrappedMediaPlayer.java
- example/lib/main.dart
- ios/Classes/AudioplayersPlugin.m
- lib/audioplayers.dart
For resolving [#83](https://github.com/luanpotter/audioplayers/issues/83).
> change play&seek position to milliseconds and add testing example

- lib/audio_cache.dart
- lib/audioplayers.dart
Check the reviews down below to understand the changes.
> Code and comments details

- lib/audioplayers.dart
> Improvements for testing

- README.md
- doc/audio_cache.md
- example/lib/main.dart
- example/lib/player_widget.dart
- lib/audio_cache.dart
- lib/audioplayers.dart
- test/audio_cache_test.dart
- test/audioplayers_test.dart
Most changes are related to documentation, but I also made some minor changes at the code and created a `dispose` method that closes all `StreamController`s.
> Improve documentation

- android/src/main/java/xyz/luan/audioplayers/AudioplayersPlugin.java
- example/lib/main.dart
- ios/Classes/AudioplayersPlugin.m
- lib/audioplayers.dart
I have added getDuration method to get the duration after setting "setUrl" for a local file to get the duration
I have this requirement for my own project to know the duration of a local file.
I can see your code is only updating the stream with this information only when you start playing a file. I understand this if you are streaming a file form internet but if you already have the file in your own device it make sense to know the duration before playing it.
Please note that I don't need nor use audio_cache because i can see it copies to a temp dir the file i already have in my system which is not in my assets. Nevertheless i can see this class uses Audioplayer under the hood.
I haven't add tests although i tried but i think it doesn't make sense because test have a fake channel
Anyway …
> Adding getDuration feature iOS/Android

- android/src/main/java/xyz/luan/audioplayers/AudioplayersPlugin.java
- ios/Classes/AudioplayersPlugin.m
- lib/audioplayers.dart
For issue #138 creating this PR. This requirement is already discussed.  Its a simple implementation with changes done in 3 files.
I have testing them both in android and iOS and works fine without any issue. Very similar to #195 .
Please lemme know if i should do anything with respect to this.
Cheers,
Venkat.
> added getCurrentPosition on iOS and Android

- README.md
troubshooting => troubleshooting
> fixed wrong word

- example/lib/player_widget.dart
Remove keyword `new` and replace `CircularProgressIndicator` to use `Slider` with `seek`
> Improve audio player example

- doc/audio_cache.md
> fix method name in audio_cache documentation

- README.md
- ios/Classes/AudioplayersPlugin.m
- lib/audioplayers.dart
fixes #277 
I've tested this on my app and it's working perfectly.
> fix broken getCurrentPosition method

- example/lib/player_widget.dart
- ios/Classes/AudioplayersPlugin.m
- lib/audioplayers.dart
A new callback to listen to player state change from notification area.   onNotificationPlayerStateChanged is similar to existing onPlayerStateChanged except that onNotificationPlayerStateChanged is called when a user interacts through the notification area. This is useful to change the app UI based on user interaction in the notification area.
> callback when player is played/paused through notification area

- ios/Classes/AudioplayersPlugin.m
- lib/audioplayers.dart
@luanpotter these are some final fixes I made to the notification area and also made the code more stable. Please merge it if its fine.
> audio notification area fixes

- CHANGELOG.md
- lib/audioplayers.dart
There was some iOS notifications code which is implemented on iOS but on android yet. I added a platform check to ignore that code on android.
Bug fix for #328 and #306
> bug fix for android version

- CHANGELOG.md
- lib/audioplayers.dart
fixes flame-engine/flame/issues/141, tested only in android.
> Removes old AudioPlayers when hot restarted

- example/lib/main.dart
- example/lib/player_widget.dart
- lib/audio_cache.dart
- lib/audioplayers.dart
Because of backward compatibility i didn't remove isLocal from constructor but i  removed every isLocal parameter from example and check  example worked properly. I made a prediction for windows local file address (third logical express line 348).
> Automatic detect address is local or remote.

- CHANGELOG.md
- README.md
- android/src/main/java/xyz/luan/audioplayers/AudioplayersPlugin.java
- android/src/main/java/xyz/luan/audioplayers/Player.java
- android/src/main/java/xyz/luan/audioplayers/WrappedMediaPlayer.java
- android/src/main/java/xyz/luan/audioplayers/WrappedSoundPool.java
- example/lib/main.dart
- example/lib/player_widget.dart
- ios/Classes/AudioplayersPlugin.m
- lib/audioplayers.dart
- pubspec.lock
- pubspec.yaml
Added playback rate for Android (setPlaybackRate method).
Thanks to [Weststreet](https://github.com/Weststreet) for his code.
> added playback rate (speed)

- darwin/Classes/AudioplayersPlugin.m
@PonnamKarthik I'm moving your changes to here in order to rebase to master and apply fixes
> applying PonnamKarthik fix

- darwin/Classes/AudioplayersPlugin.m
Just changed the code such that the notifcation image is now brought in async fashion to remove any freezing UI and improving performance.
> Notification area image in async 

- lib/audioplayers.dart
Detect url is local just work in play function after this change, setUrl() function detect url too.
> Add checking url is local to setUrl function

- .github/workflows/build.yaml
- example/lib/generated_plugin_registrant.dart
I'm fixing version `1.14.x` because ios started to break on current beta version.
> Test android emulator with flutter drive

- darwin/Classes/AudioplayersPlugin.m
https://github.com/luanpotter/audioplayers/issues/425
> add availability check to fix warning messages during iOS build

- .github/workflows/pull-request.yaml
This will fix ytour readme badge
> Add "pull request" workflow

- CHANGELOG.md
- analysis_options.yaml
- example/lib/generated_plugin_registrant.dart
- lib/audio_cache.dart
- lib/audioplayers_web.dart
- pubspec.lock
- pubspec.yaml
This is a second try on flutter web, using the dart_web_audio that I created, following instructions from the Google/Flutter team.
> Using new dart_web_audio package to provide web support

- example/lib/generated_plugin_registrant.dart
- lib/audioplayers_web.dart
- pubspec.lock
- pubspec.yaml
Fix for https://github.com/luanpotter/audioplayers/issues/482
This should be working on release mode as well as debug/profile modes.
> Fix to work on release mode

- example/macos/Flutter/GeneratedPluginRegistrant.swift
- example/macos/Podfile.lock
- ios/audioplayers.podspec
- macos/audioplayers.podspec
> update license path

- darwin/Classes/AudioplayersPlugin.m
> Fix can't play on iOS.

- CHANGELOG.md
- lib/audio_cache.dart
- lib/audioplayers.dart
- lib/audioplayers_web.dart
- pubspec.yaml
> Fix Exception thrown when calling audioPlayer.dispose

- CHANGELOG.md
- darwin/Classes/AudioplayersPlugin.m
- example/lib/player_widget.dart
- lib/audio_cache.dart
- lib/audioplayers.dart
Rebased and fixed iOS next and prev buttons rather than the default video controls
> Fix ios next prev controls

- .github/workflows/build.yaml
- .github/workflows/pull-request.yaml
It seems to be sorted by recency and I just grab the first one. I don't want to have to change this...
> Fixes the build forever by using the latest iphone version instead of hardcoding

- lib/audioplayers.dart
@renancaraujo since you added this can you take a look to see if I am not wrong?
> Improve docs around player state

- README.md
- feature_parity_table.md
- pubspec.lock
I still need to properly go through each example app on each platform to make sure the table is correctly filled w/o any bugs.
Hopefully I can add some automated tests on our suite for at least some of the platforms.
But I am opening this for feedback on the structure and suggestions so far.
> Add draft of a feature parity table

- .github/workflows/build.yaml
- .github/workflows/pull-request.yaml
- darwin/Classes/NotificationsHandler.swift
- darwin/Classes/SwiftAudioplayersPlugin.swift
- darwin/Classes/Utils.swift
- darwin/Classes/WrappedMediaPlayer.swift
- ios/Classes/NotificationsHandler.swift
- ios/Classes/Utils.swift
- ios/Classes/WrappedMediaPlayer.swift
- lib/audioplayers.dart
- macos/Classes/NotificationsHandler.swift
- macos/Classes/Utils.swift
- macos/Classes/WrappedMediaPlayer.swift
- pubspec.lock
This is the second step. A bit more organized.
Adding a WrappedMediaPlayer class to parallel android, and extracting the notification code to a third file.
> Split darwin code into a few files for better organization and understanding

- CHANGELOG.md
- troubleshooting.md
This will close issues #455 and #377
> Add more useful info to the troubleshoot guide.

- android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt
- android/src/main/kotlin/xyz/luan/audioplayers/ByteDataSource.kt
- android/src/main/kotlin/xyz/luan/audioplayers/Player.kt
- android/src/main/kotlin/xyz/luan/audioplayers/WrappedMediaPlayer.kt
- android/src/main/kotlin/xyz/luan/audioplayers/WrappedSoundPool.kt
- darwin/Classes/NotificationsHandler.swift
- darwin/Classes/SwiftAudioplayersPlugin.swift
- darwin/Classes/WrappedMediaPlayer.swift
- example/android/app/build.gradle
- example/android/build.gradle
- example/android/gradle.properties
- example/android/gradle/wrapper/gradle-wrapper.properties
- feature_parity_table.md
- pubspec.lock
This:
* improves kotlin code by removing !! and other kt smells, make code simpler and better handle errors
* format and small improvements on the swift code
* update gradle, android, pub versions
* update the feature parity table to better reflect reality
> General improvements and refactorings

- android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt
- android/src/main/kotlin/xyz/luan/audioplayers/ByteDataSource.kt
- android/src/main/kotlin/xyz/luan/audioplayers/WrappedMediaPlayer.kt
- android/src/main/kotlin/xyz/luan/audioplayers/WrappedSoundPool.kt
Fixing the issues on #714 .
Sorry about the amount of commits, I fixed using github editing. You can rebase and squash them if needed.
> Fix Android Compilation errors

- darwin/Classes/SwiftAudioplayersPlugin.swift
- darwin/Classes/WrappedMediaPlayer.swift
> mix if duck audio is true on iOS

- lib/audioplayers.dart
> Fix warning from pub

- CHANGELOG.md
- README.md
- android/build.gradle
- example/android/app/build.gradle
> Downgrading minSdk back to 16

- .github/workflows/build.yaml
- .github/workflows/pull-request.yaml
- scripts/format.sh
Since there were some android build errors in the recent PRs, I thought it would be nice to catch these automatically.
This can probably also be done for iOS.
Btw, what is the reason for the two separate workflow files here? As far as I can see, they're doing the same. Except for the triggers.
> Simplify workflows, build example app apk

- CHANGELOG.md
- lib/audioplayers.dart
> Fix missing close resource leak

- packages/audioplayers/darwin/Classes/Utils.swift
- packages/audioplayers/darwin/Classes/WrappedMediaPlayer.swift
Local files was broken on mac os since the web PR. This fixes it.
> Fix local files for macos

- packages/audioplayers/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt
- packages/audioplayers/android/src/main/kotlin/xyz/luan/audioplayers/Logger.kt
- packages/audioplayers/android/src/main/kotlin/xyz/luan/audioplayers/WrappedSoundPool.kt
- packages/audioplayers/darwin/Classes/Logger.swift
- packages/audioplayers/darwin/Classes/NotificationsHandler.swift
- packages/audioplayers/darwin/Classes/SwiftAudioplayersPlugin.swift
- packages/audioplayers/darwin/Classes/Utils.swift
- packages/audioplayers/darwin/Classes/WrappedMediaPlayer.swift
- packages/audioplayers/example/lib/components/btn.dart
- packages/audioplayers/example/lib/components/tab_wrapper.dart
- packages/audioplayers/example/lib/generated_plugin_registrant.dart
- packages/audioplayers/example/lib/main.dart
- packages/audioplayers/example/lib/tabs/global.dart
- packages/audioplayers/ios/Classes/Logger.swift
- packages/audioplayers/lib/audioplayers.dart
- packages/audioplayers/lib/audioplayers_api.dart
- packages/audioplayers/lib/src/api/log_level.dart
- packages/audioplayers/lib/src/audioplayer.dart
- packages/audioplayers/lib/src/audioplayers_web.dart
- packages/audioplayers/lib/src/logger.dart
- packages/audioplayers/macos/Classes/Logger.swift
* Unifies our logging for all platforms
* Allows disabling native side logs
* Adds log levels
Note: there are still some platform level logs that are fired w/o our consent, but now we have the info on BE to prevent that depending on the selected log level.
> Actually wire up a proper logger between client and native sides

- .github/workflows/build.yaml
- feature_parity_table.md
- packages/audioplayers/example/pubspec.yaml
- packages/audioplayers/lib/src/audioplayer.dart
- packages/audioplayers/lib/src/audioplayers_web.dart
- packages/audioplayers/pubspec.lock
- packages/audioplayers/pubspec.yaml
- packages/audioplayers/test/audioplayers_test.dart
> Fix bug that "current position" events are not emitted in Flutter Web

- packages/audioplayers/lib/src/audioplayer.dart
> added condition to avoid adding state after screen disposing

- packages/audioplayers_darwin/darwin/Classes/SwiftAudioplayersDarwinPlugin.swift
- packages/audioplayers_darwin/darwin/Classes/WrappedMediaPlayer.swift
This is a rebase of https://github.com/bluefireteam/audioplayers/pull/1071 into the new structure
I named the lambda "Completer" (apparently swift only supports any sensible form of async/promise/future for newer devices).
I added the Completer everywhere (setSourceUrl, stop, seek).
> Rebasing implementation of #1071

- packages/audioplayers_windows/windows/audioplayers_windows_plugin.cpp
Fixes https://github.com/bluefireteam/audioplayers/issues/1095
> Fix setPlayerMode on windows

- .github/workflows/build.yaml
- packages/audioplayers_darwin/darwin/Classes/WrappedMediaPlayer.swift
I don't understand how this happened, xcode was tricking me and the build passed...
> fix: Fix iOS code that was missing from previous push

- packages/audioplayers_web/lib/wrapped_player.dart
Opening this to push some changes to https://github.com/bluefireteam/audioplayers/pull/1115 before merging
> feat: Add onPlayerCompletion, onPlayerStateChanged and onDurationChanged for web

- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/WrappedPlayer.kt
> fix(android): getDuration, getPosition causes MEDIA_ERROR_UNKNOWN

- getting_started.md
This stream no longer exists. It was actually never fired anywhere. A relic of the past.
> docs: Remove outdated reference from docs

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/pull_request_template.md
I noticed many of the issues aren't filled correctly.
This may has to do with the time you have to invest to tackle each point in the issue template.
I tried to simplify this a bit and comment out the explanations. 
- The issue creator can easily see what is missing
- The reviewer can see how much effort is put in a bug report/feature request and also gets more compact information (I hope so at least)
I oriented on the [flutter templates](https://github.com/flutter/flutter/tree/master/.github) and the [flame templates](https://github.com/flame-engine/flame/tree/main/.github)
No related issues
[Conventional …
> chore: update github templates

- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/WrappedPlayer.kt
We should make sure to have this or similar description in the merge commit:
fix(android):
- handle only one `UpdateRunnable` per plugin lifecycle, fix missing position updates when not stopped previously; add `IUpdateCallback`
- avoid player.stop and player.pause if not prepared (closes #139)
- proper support for live streams (start / stop / no seeking)
- always create new player, when player mode has changed
- reset prepared variable, when setting player mode
- set player via `initPlayer` before onPrepared is called
- avoid `actuallyPlay` if in released state
- reset source to null, if released; fix setting same source after release
- always reset shouldSeekTo=-1 when seek was performed
- refactor `positionUpdates` to `updates` as it also handles duration events
[issue database]: …
> fix(android): bugs from integration tests

- .github/workflows/build.yaml
- packages/audioplayers/lib/src/audio_cache.dart
- packages/audioplayers/lib/src/audioplayer.dart
- packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart
- fix linting
- switch to stable channel for web
Also necessary to fix CI, which fails on flutter analyze.
> chore: support flutter 3.3.0

- packages/audioplayers/example/.metadata
- packages/audioplayers/example/android/.gitignore
- packages/audioplayers/example/android/app/build.gradle
- packages/audioplayers/example/android/app/src/debug/AndroidManifest.xml
- packages/audioplayers/example/android/app/src/main/AndroidManifest.xml
- packages/audioplayers/example/android/app/src/main/res/values-night/styles.xml
- packages/audioplayers/example/android/app/src/main/res/values/styles.xml
- packages/audioplayers/example/android/app/src/profile/AndroidManifest.xml
- packages/audioplayers/example/android/build.gradle
- packages/audioplayers/example/android/gradle/wrapper/gradle-wrapper.properties
- packages/audioplayers/example/pubspec.yaml
- packages/audioplayers/pubspec.yaml
- packages/audioplayers_android/android/build.gradle
- packages/audioplayers_android/android/settings.gradle
Upgrade android modules and dependencies:
- Recreate `example` android project to apply flutter best practices
- Upgrade dependencies: kotlin, gradle, path_provider
- Bump  compile sdk version
- Add android suffix to android module to comply with naming, e.g. see [Pathprovider](https://github.com/flutter/plugins/blob/main/packages/path_provider/path_provider_android/android/settings.gradle)
> chore(android): upgrade android modules and dependencies

- packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart
Fixes a floating promise
Fixes #1253
> fix(audioplayers_platform_interface): handle platform exception via logger

- packages/audioplayers/example/lib/components/player_widget.dart
- packages/audioplayers/example/lib/components/tgl.dart
- packages/audioplayers/example/lib/generated_plugin_registrant.dart
- packages/audioplayers/example/lib/main.dart
- packages/audioplayers/example/lib/tabs/controls.dart
- packages/audioplayers/example/lib/tabs/sources.dart
- packages/audioplayers/example/lib/tabs/streams.dart
- packages/audioplayers/example/lib/utils.dart
- packages/audioplayers/example/pubspec.yaml
* no need to stop on playerComplete event
* reset position to zero on playerComplete event
* keys for TextWidgets of values in `Tgl`
* keys for TextWidgets in toasts
* make some methods private
* format displayed numbers to be consistent
* setSource via file picker
* button to get current player state
* set release mode to stop by default
* handle `onPlayerComplete` and onSeekComplete` globally to be able to display toasts across tabs
Improve example to be compatible with upcoming tests.
[example]: …
> feat: improve example

- packages/audioplayers/example/integration_test/tabs/controls_tab.dart
- packages/audioplayers/example/lib/tabs/sources.dart
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/MediaPlayerPlayer.kt
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/Player.kt
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/SoundPoolPlayer.kt
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/WrappedPlayer.kt
* ignoring live stream
* reset streamId on stop
Fix issues with lowLatency and add according tests.
closes #1176, closes #1193, closes #1165
> fix(android): lowLatency bugs (closes #1176, closes #1193, closes #1165)

- getting_started.md
> docs: Replace outdated code from docs

- getting_started.md
pause method will not resume, it will pause or stop on the current position
> docs: Pause method comment rectified

- packages/audioplayers_platform_interface/lib/audioplayers_platform_interface.dart
- packages/audioplayers_platform_interface/lib/streams_interface.dart
- packages/audioplayers_web/lib/wrapped_player.dart
Remove unused player state stream. See [this comment](https://github.com/bluefireteam/audioplayers/pull/1257#discussion_r967503459).
BREAKING CHANGE: But it should not play a role:
- stream was never called, so it never emitted any events, (except for web, which also already emits `onComplete` event). So most likely no-one did listen to this stream.
- the according stream is further exposed in main `audioplayers` package, so it's not breaking the main package.
#1257
[example]: https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/ex …
> refactor!: remove unused playerStateStream

- .github/workflows/build.yaml
* fix ios simulator UDID
* consistent naming
Improve CI
> chore(tests): only execute tests, if is no draft

- .github/workflows/stale.yml
I think it's not necessary to execute `changes-requested` every hour. Once a day should be fine.
I also added a `stale` cron.
- `changes-requested`: if a issue or merge request doesn't fulfill the conventions and has to be changed by the author. Closes after one week.
- `stale`: if no activity is recognized and the issue cannot help fixing a bug or adding a feature in the current state. Closes after one month.
- `waiting for report`: wait for a response of the author, but not necessarily need to close the issue.
> chore: reduce frequency of changes requested cron, add stale cron

- CHANGELOG.md
- packages/audioplayers/CHANGELOG.md
- packages/audioplayers/example/pubspec.yaml
- packages/audioplayers/pubspec.yaml
- packages/audioplayers_android/CHANGELOG.md
- packages/audioplayers_android/pubspec.yaml
- packages/audioplayers_darwin/CHANGELOG.md
- packages/audioplayers_darwin/pubspec.yaml
- packages/audioplayers_web/CHANGELOG.md
- packages/audioplayers_web/pubspec.yaml
- audioplayers@1.1.1
- audioplayers_android@1.1.1
- audioplayers_darwin@1.0.3
- audioplayers_web@2.0.1
> chore(release): publish packages

- troubleshooting.md
Update the links for supported audio codecs
> docs: update links for audio codecs

- .github/workflows/build.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
* ability to trigger each job individually via workflow_dispatch
* categorize reusable workflows / jobs into `build` and `test`
* split trigger into `pull-request` and `release`
#1333
> chore(workflows): customizable workflows

- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/WrappedPlayer.kt
> chore: Fix formatting of kotlin code

- packages/audioplayers_platform_interface/lib/api/audio_context_config.dart
There has been a high number of issues being opened around the fact that on 1.0.0, `forceSpeaker` on iOS (and android) was set to `false` by default, requiring most users to explicitly setup the global audio context.
This change the default value of iOS audio context to force speakers to be inline with what users seem to expect.
Follow [this thread](https://github.com/bluefireteam/audioplayers/issues/1194) for details.
Since I only test iOS on emulators, where this setting doesn't make any difference, I hadn't realized this issue.
Note: this changes the default for android as well, which is in line with the unified audio context philosophy.
If you wanted to have it set to false, you can just set it so:
```dart
final AudioContext audioContext = AudioContext(
iOS: AudioContextIOS( …
```
> fix!: Change the default value of iOS audio context to force speakers

- README.md
This fixes some 404s for links to other documentation.
Relative links in pub.dev would lead to 404s in github. On the documentation page of pub.dev it would lead to 404s on pub.dev
Instead the links have been changed to link directly to `https://github.com/bluefireteam/audioplayers/blob/main`.
Fixes https://github.com/bluefireteam/audioplayers/issues/1367
> fix: Replace relative links in readme

- troubleshooting.md
Use official docs to provide information about valid audio formats / codecs
> docs: Update audio format links for iOS / macOS

- feature_parity_table.md
- getting_started.md
- migration_guide.md
- troubleshooting.md
Just fixes some small typos, and bumps the version in the migration doc.
> docs: Fix typos

- .github/workflows/build-example.yml
- .github/workflows/test.yml
CI gives some warnings about the java action.
See e.g.:
https://github.com/bluefireteam/audioplayers/actions/runs/3903397234
> ci: upgrade setup-java action to v3

- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/MediaPlayerPlayer.kt
This pull request fix issue #1344.
Use approach in PR #1389.
Add sdk version checking on MediaPlayerPlayer setRate.
Don't throw exception when rate equals to 1.0
Fixes #1344
> fix(android): playing at playback rate `1.0` in android API level < 23 (fixes #1344)

- packages/audioplayers/example/android/app/src/main/AndroidManifest.xml
- packages/audioplayers/example/integration_test/tabs/controls_tab.dart
- packages/audioplayers/example/integration_test/tabs/properties.dart
- packages/audioplayers/example/integration_test/tabs/stream_tab.dart
- packages/audioplayers/example/integration_test/test_utils.dart
- packages/audioplayers/example/lib/components/btn.dart
- packages/audioplayers/example/lib/components/cbx.dart
- packages/audioplayers/example/lib/components/dlg.dart
- packages/audioplayers/example/lib/components/drop_down.dart
- packages/audioplayers/example/lib/components/indexed_stack.dart
- packages/audioplayers/example/lib/components/list_tile.dart
- packages/audioplayers/example/lib/components/player_widget.dart
- packages/audioplayers/example/lib/components/properties_widget.dart
- packages/audioplayers/example/lib/components/stream_widget.dart
- packages/audioplayers/example/lib/components/tab_content.dart
- packages/audioplayers/example/lib/components/tgl.dart
- packages/audioplayers/example/lib/main.dart
- packages/audioplayers/example/lib/tabs/audio_context.dart
- packages/audioplayers/example/lib/tabs/controls.dart
- packages/audioplayers/example/lib/tabs/logger.dart
- packages/audioplayers/example/lib/tabs/sources.dart
- packages/audioplayers/example/lib/tabs/streams.dart
- packages/audioplayers/example/lib/utils.dart
- add ability to change Android and iOS specific contexts
- Permission for WAKE_LOCK and MODIFY_AUDIO_SETTINGS
- improved layout of widgets (more spacing, responsive height, etc.)
- preserve state for each player
- style toggles
- add some icons
> feat: example improvements

- README.md
Since most people probably aren't looking for that commit anymore I generalized the note a bit.
> docs: Update note about documentation in readme

- packages/audioplayers/example/macos/Podfile
- packages/audioplayers/example/macos/Podfile.lock
- packages/audioplayers/example/macos/Runner.xcodeproj/project.pbxproj
- packages/audioplayers/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
Update missing macos project files from updating #1419
> chore: update macos project files of example

- packages/audioplayers/example/lib/tabs/logger.dart
- packages/audioplayers/example/server/pubspec.yaml
- packages/audioplayers/lib/src/log_level.dart
- packages/audioplayers/lib/src/logger.dart
- packages/audioplayers/pubspec.yaml
- packages/audioplayers/test/audio_cache_test.dart
- packages/audioplayers_android/pubspec.yaml
- packages/audioplayers_darwin/pubspec.yaml
- packages/audioplayers_linux/pubspec.yaml
- packages/audioplayers_platform_interface/pubspec.yaml
- packages/audioplayers_web/pubspec.yaml
- packages/audioplayers_windows/pubspec.yaml
- Upgrade min Dart to v2.7.0
- Upgrade min Flutter to v3.0.0 
Don't exactly know if this counts as breaking as it more depends on the environment than on the code itself..., maybe.
#1352
> chore: Upgrade minimum Dart & Flutter versions

- packages/audioplayers/example/integration_test/lib_test.dart
Test to play a non existent url
Closes #92
> test: play non existent url (closes #92)

- CHANGELOG.md
- packages/audioplayers/CHANGELOG.md
- packages/audioplayers/example/pubspec.yaml
- packages/audioplayers/pubspec.yaml
- packages/audioplayers_android/CHANGELOG.md
- packages/audioplayers_android/pubspec.yaml
- packages/audioplayers_darwin/CHANGELOG.md
- packages/audioplayers_darwin/pubspec.yaml
- packages/audioplayers_linux/CHANGELOG.md
- packages/audioplayers_linux/pubspec.yaml
- packages/audioplayers_web/CHANGELOG.md
- packages/audioplayers_web/pubspec.yaml
- packages/audioplayers_windows/CHANGELOG.md
- packages/audioplayers_windows/pubspec.yaml
- audioplayers@4.0.1
- audioplayers_android@3.0.1
- audioplayers_darwin@4.0.1
- audioplayers_linux@2.0.1
- audioplayers_web@3.0.1
- audioplayers_windows@2.0.1
> chore(release): Publish 4.0.1

- packages/audioplayers/example/integration_test/test_utils.dart
- packages/audioplayers/example/lib/components/btn.dart
- packages/audioplayers/example/lib/components/cbx.dart
- packages/audioplayers/example/lib/components/dlg.dart
- packages/audioplayers/example/lib/components/drop_down.dart
- packages/audioplayers/example/lib/components/list_tile.dart
- packages/audioplayers/example/lib/components/pad.dart
- packages/audioplayers/example/lib/components/player_widget.dart
- packages/audioplayers/example/lib/components/properties_widget.dart
- packages/audioplayers/example/lib/components/stream_widget.dart
- packages/audioplayers/example/lib/components/tab_content.dart
- packages/audioplayers/example/lib/components/tabs.dart
- packages/audioplayers/example/lib/components/tgl.dart
- packages/audioplayers/example/lib/components/txt.dart
- packages/audioplayers/example/lib/main.dart
- packages/audioplayers/example/lib/tabs/audio_context.dart
- packages/audioplayers/example/lib/tabs/controls.dart
- packages/audioplayers/example/lib/tabs/logger.dart
- packages/audioplayers/example/lib/tabs/sources.dart
- packages/audioplayers/example/lib/tabs/streams.dart
- packages/audioplayers/lib/src/audio_pool.dart
- packages/audioplayers/test/logger_test.dart
- packages/audioplayers_web/lib/audioplayers_web.dart
- packages/audioplayers_web/lib/wrapped_player.dart
Adapt code to comply with new lint rules published in `flame_lint` v0.2.0+2
> refactor: Adapt to flame_lint v0.2.0+2

- .github/workflows/build-example.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- melos.yaml
- packages/audioplayers/example/android/app/build.gradle
- packages/audioplayers/example/integration_test/lib_test.dart
- packages/audioplayers/example/pubspec.yaml
- packages/audioplayers/example/server/pubspec.yaml
- packages/audioplayers/lib/src/audio_cache.dart
- packages/audioplayers/lib/src/audioplayer.dart
- packages/audioplayers/pubspec.yaml
- packages/audioplayers_android/pubspec.yaml
- packages/audioplayers_darwin/pubspec.yaml
- packages/audioplayers_linux/pubspec.yaml
- packages/audioplayers_platform_interface/lib/src/audioplayers_platform.dart
- packages/audioplayers_platform_interface/pubspec.yaml
- packages/audioplayers_web/pubspec.yaml
- packages/audioplayers_windows/pubspec.yaml
- Compatibility with min flutter version
- Allow configure Flutter version in dispatch workflow.
> fix: test and fix compatibility with min flutter version

- packages/audioplayers/pubspec.yaml
- pubspec.yaml
Upgrade range for package `file: '>=6.1.0 <8.0.0'`
Closes #1541 
Dependent on `path_provider`, `xdg_directories`, https://github.com/google/process.dart/pull/75
> chore: upgrade range for package `file`

- .github/workflows/build-example.yml
See https://github.com/flutter/flutter/pull/127628
> ci(android): Support proguard rules for AGP8

- CHANGELOG.md
- packages/audioplayers/CHANGELOG.md
- packages/audioplayers/example/pubspec.yaml
- packages/audioplayers/pubspec.yaml
- packages/audioplayers_android/CHANGELOG.md
- packages/audioplayers_android/pubspec.yaml
- packages/audioplayers_darwin/CHANGELOG.md
- packages/audioplayers_darwin/pubspec.yaml
- packages/audioplayers_linux/CHANGELOG.md
- packages/audioplayers_linux/pubspec.yaml
- packages/audioplayers_platform_interface/CHANGELOG.md
- packages/audioplayers_platform_interface/pubspec.yaml
- packages/audioplayers_web/CHANGELOG.md
- packages/audioplayers_web/pubspec.yaml
- packages/audioplayers_windows/CHANGELOG.md
- packages/audioplayers_windows/pubspec.yaml
- audioplayers@5.0.0
- audioplayers_android@4.0.0
- audioplayers_darwin@5.0.0
- audioplayers_linux@3.0.0
- audioplayers_platform_interface@6.0.0
- audioplayers_web@4.0.0
- audioplayers_windows@3.0.0
> chore(release): Publish audioplayers 5.0.0

- packages/audioplayers/example/lib/components/properties_widget.dart
- packages/audioplayers/lib/src/audioplayer.dart
- packages/audioplayers/test/audioplayers_test.dart
> feat: Get current volume, balance and playbackRate

- .github/workflows/test.yml
V1 has issues downloading the newest chrome version. Switching to setup-chromedriver v2
See e.g. https://github.com/bluefireteam/audioplayers/actions/runs/5696734896/job/15442357926?pr=1585
> ci: update action setup-chromedriver

- CHANGELOG.md
- packages/audioplayers/CHANGELOG.md
- packages/audioplayers/example/pubspec.yaml
- packages/audioplayers/pubspec.yaml
- packages/audioplayers_android/CHANGELOG.md
- packages/audioplayers_android/pubspec.yaml
- packages/audioplayers_darwin/CHANGELOG.md
- packages/audioplayers_darwin/pubspec.yaml
- audioplayers@5.1.0
- audioplayers_android@4.0.1
- audioplayers_darwin@5.0.1
> chore(release): Publish 5.1.0

- .github/workflows/build-example.yml
- .github/workflows/test.yml
- Upgrade flutter version to 3.10.6
- Change workflow_dispatch version to `any`
> ci: Upgrade flutter version to 3.10.6

- .github/workflows/build.yml
- .github/workflows/test.yml
See #1570, #1599, #1603
See #1570, #1599, #1603
> ci: Disable Hyper-V time sync for Windows, reenable Scream as Virtual Audio Device

- .github/workflows/build-example.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- packages/audioplayers/example/lib/tabs/audio_context.dart
- packages/audioplayers/example/lib/tabs/controls.dart
- packages/audioplayers/example/lib/tabs/logger.dart
- packages/audioplayers_linux/pubspec.yaml
- Adapt linting
- audioplayers_linux: raise min Flutter version to 3.13.0 due to flutter/flutter#129534
- Raise min testing Flutter version to 3.13.0 due to flutter/flutter#129534, flutter/flutter#127628, flutter/flutter#125657
If using platform linux change pubspec.yaml:
Before:
```yaml
environment:
flutter: '>=3.10.x'
```
After:
```yaml
environment:
flutter: '>=3.13.0'
```
> chore!: Upgrade to Flutter 3.13.0

- packages/audioplayers/pubspec.yaml
> chore: Update range for package `uuid` (closes #1627)

- packages/audioplayers/example/lib/components/dlg.dart
- packages/audioplayers/example/lib/tabs/controls.dart
- packages/audioplayers/example/lib/tabs/sources.dart
Update the example to allow playing custom media sources.
Closes #1622.
#1622
> feat: Allow adding custom media sources to example

- packages/audioplayers/lib/src/audioplayer.dart
If an error occurred during setting the source, the `onPreparedSubscription` was still listened to, although it is not needed anymore. This triggered a `Future already completed` error.
Fixes #1642
> fix: Cancel `onPreparedSubscription` on error

- CHANGELOG.md
- packages/audioplayers/CHANGELOG.md
- packages/audioplayers/example/pubspec.yaml
- packages/audioplayers/pubspec.yaml
- packages/audioplayers_android/CHANGELOG.md
- packages/audioplayers_android/pubspec.yaml
- packages/audioplayers_darwin/CHANGELOG.md
- packages/audioplayers_darwin/pubspec.yaml
- packages/audioplayers_linux/CHANGELOG.md
- packages/audioplayers_linux/pubspec.yaml
- packages/audioplayers_platform_interface/CHANGELOG.md
- packages/audioplayers_platform_interface/pubspec.yaml
- packages/audioplayers_web/CHANGELOG.md
- packages/audioplayers_web/pubspec.yaml
- packages/audioplayers_windows/CHANGELOG.md
- packages/audioplayers_windows/pubspec.yaml
These are just the changelogs for v5.2.0 et. al.
> chore: Publish 5.2.0

- .github/workflows/pull-request.yml
If want to create a PR against a branch other than main, the tests are not executed. As there are very few of the mentioned PRs and it is more error prone, I propose to enable these, to better maintain other `release` branches.
> ci: Run tests on all pull request

- packages/audioplayers/example/integration_test/app_test.dart
- packages/audioplayers/example/lib/tabs/sources.dart
> test: Update invalid m3u8 stream url

- getting_started.md
> docs: Update deprecated `setGlobalAudioContext` to `setAudioContext`

- getting_started.md
This was what I was looking for in the documentation.
> docs: Add setReleaseMode example

- packages/audioplayers_web/lib/wrapped_player.dart
- packages/audioplayers_web/pubspec.yaml
The package `web` 1.0.0 was released, which cannot be used currently with audioplayers. 
> deps: Consider web:1.0.0

- .github/workflows/release-prepare.yml
- .github/workflows/release-publish.yml
- .github/workflows/release-tag.yml
Apply semi-automation feature from the melos-action.
> ci: Semi-automate publish process

- .github/workflows/build-example.yml
- .github/workflows/test.yml
- packages/audioplayers/example/android/gradle/wrapper/gradle-wrapper.properties
- packages/audioplayers/example/android/settings.gradle
> ci: Upgrade to Flutter v3.27.x, support ubuntu-24.04 runner

- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/FocusManager.kt
Another try to fix messed audio focus
Closes #1876
> fix: Change audioFocus dynamically

- .github/workflows/build-example.yml
- .github/workflows/build.yml
See failure of: https://github.com/bluefireteam/audioplayers/actions/runs/13168116351/job/36752949630
> ci: Fix deploy to pages

- .github/workflows/pull-request.yml
- packages/audioplayers/example/ios/Podfile.lock
- packages/audioplayers/example/ios/Runner.xcodeproj/project.pbxproj
- packages/audioplayers/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/audioplayers/example/ios/Runner/AppDelegate.swift
- packages/audioplayers/example/macos/Podfile.lock
- packages/audioplayers/example/macos/Runner.xcodeproj/project.pbxproj
- packages/audioplayers/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/audioplayers/example/macos/Runner/AppDelegate.swift
Update files needed for publishing
> chore: Update darwin platform files

- packages/audioplayers/example/macos/Flutter/GeneratedPluginRegistrant.swift
Forgot to hit `flutter pub upgrade` before running.
> chore: Update macos plugin registrant

- .github/workflows/test.yml
Most likely a bug due to https://github.com/flutter/flutter/issues/106277 among others.
> ci: Enable tests on macOS

- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/FocusManager.kt
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/WrappedPlayer.kt
- packages/audioplayers_android_exo/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt
- packages/audioplayers_android_exo/android/src/main/kotlin/xyz/luan/audioplayers/player/WrappedPlayer.kt
> fix: Make FocusManager compatible with Android API <= 25 (closes #1895)

- packages/audioplayers/lib/src/audioplayer.dart
- packages/audioplayers/lib/src/global_audio_scope.dart
- packages/audioplayers/test/audioplayers_test.dart
- packages/audioplayers/test/fake_global_audioplayers_platform.dart
- packages/audioplayers/test/global_audioplayers_test.dart
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt
- packages/audioplayers_android_exo/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt
- packages/audioplayers_darwin/darwin/Classes/SwiftAudioplayersDarwinPlugin.swift
- packages/audioplayers_linux/linux/audioplayers_linux_plugin.cc
- packages/audioplayers_platform_interface/lib/src/global_audioplayers_platform.dart
- packages/audioplayers_platform_interface/lib/src/global_audioplayers_platform_interface.dart
- packages/audioplayers_platform_interface/lib/src/method_channel_extension.dart
- packages/audioplayers_web/lib/global_audioplayers_web.dart
- packages/audioplayers_windows/windows/audioplayers_windows_plugin.cpp
> feat: Dispose players on Hot restart (closes #1120)
