bluefireteam/audioplayers

- android/src/main/java/bz/rxla/audioplayer/AudioplayerPlugin.java
Android:
If the user pauses a audio session and press play again a IllegalStateException occurs.
> fix IllegalStateException on play -> pause -> play

- lib/audioplayer.dart
If you run the existing audio player with Dart 2 type checks, it fails because invokeMethod returns a Future<dynamic> rather than a Future<int>. This change explicitly casts the return type as an int so that the signature can remain the same.
> Made audioplayer dart2 compatible.

- ios/Classes/AudioplayersPlugin.m
Corrected a bug that was causing a player to loop forever if it was stopped by a dart channel command some moments before its end.
> Avoid restarting a looping player if is stopped

- doc/audio_cache.md
Trivial stuff really, but this will safe other peoples time a bit.
The only surprise here might be that `const` had to go. The invoked constructor isn't a const constructor (anymore?).
> Fix some errors in the examples and markdown

- ios/Classes/AudioplayersPlugin.m
This pull request fixed following 2 issues
1. There is no voice when it's speaker mode(no headphone plugged in) on real iOS device, see #33 for details.
2. It's not working for iOS background mode even background modes has been enabled in Capacities when building the app. see #35 for details.
> Fix iOS speaker and background mode not working issue

- lib/audio_cache.dart
pubspec.yaml
```yaml
assets:
- assets/
- assets/漢字/
- assets/audio/
- assets/audio/音/
- assets/audio/音声/
```
main.dart
```dart
AudioCache player = new AudioCache(prefix: 'audio/');
void playVoice(fileName) {
player.play(p.join('音声', fileName));
}
```
audio_cache.dart
```dart
final file = new File('${(await getTemporaryDirectory()).path}/$fileName');
/* File's path is "/data/.../cache/audio/音声/a.mp3", but 
the directories from the cache directory leading up to
the file haven't been created yet, so unless we call 
`create` recursively, attempting to write data to the
file will fail */
await file.create(recursive: true);
return await file
.writeAsBytes((await _fetchAsset(fileName)).buffer.asUint8List());
```
> allow for nested assets in cache

- ios/Classes/AudioplayersPlugin.m
I deleted *channel variable because of not using and changed _channel variable to _channel_audioplayer, because of duplicate symbol with firebase_admob.
I tested from ios simulator and it worked!
> edit variable name _channel to _channel_audioplayer (issue #34)

- .gitignore
- android/src/main/java/xyz/luan/audioplayers/WrappedMediaPlayer.java
- example/ios/Runner.xcodeproj/project.pbxproj
- ios/Classes/AudioplayersPlugin.m
The "play" and "setUrl" methods return before the player is actually ready.
If "seek" is called too soon, the Android layer will throw an error.
To fix this, we store seek operations on the Android side until the player is ready and then execute the most recent one once it is.
> Delay seek operations on Android until player is ready.

- android/src/main/java/xyz/luan/audioplayers/AudioplayersPlugin.java
- example/lib/player_widget.dart
- ios/Classes/AudioplayersPlugin.m
- lib/audioplayers.dart
Currently audio files must start playing from the beginning. This PR adds the optional functionality of setting the playback position to the `play` function (calls `seek` during player setup calling `play`).
> Allow setting seek position in play function

- README.md
- example/lib/player_widget.dart
- lib/audioplayers.dart
Now instead of defining callbacks, users can listen to streams instead.
Addresses #86
> Added Streams to replace callbacks

- lib/audioplayers.dart
Changes to the current duration are broadcast to the position change stream, rather than to the duration change stream. 
This should fix that.
> Fix duration changes being broadcast on position change stream

- lib/audioplayers.dart
Commit https://github.com/luanpotter/audioplayers/commit/552f76823a7faa386ee4120ace29568e43a7291e#r32561884 breakes PR #85 oslo registered as Issue #84
Default position should be `null` because of login in line 162:
```final double positionInSeconds = position == null ? null : position.inSeconds.toDouble();```
> Fix default position value for play method.

- example/ios/Runner.xcodeproj/project.pbxproj
- example/ios/Runner/AppDelegate.swift
- ios/Classes/AudioplayersPlugin.m
1. Upgrade to Swift5 in example project setting. 
`The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 4.0, 4.2, 5.0. This setting can be set in the build settings editor.`
2. Fix Warning of `warning: format specifies type 'double' but the argument has type 'int' [-Wformat]"`
> Upgrade to Swift 5 in example project setting

- lib/audioplayers.dart
A while ago I sent #168, adding the `dispose()` method. Today I realized my change was pretty incondite, since I did not annotate the return type and did not wait for the `StreamController`s to close. With this PR I'm fixing it.
Please notice that `StreamController.close()` will never complete if no one is listening to its stream, however this does not proceed for `BroadcastStreamController`s, which you are using, so there should be no concerns. I'm emphasizing this so you are aware of possible problems in case you decide to not use `BroadcastStream`s anymore.
> Improve `dispose()` method.

- lib/audioplayers.dart
isLocal now shows that it should be false when the file path is a remote URL.
> isLocal description fixed

- android/src/main/java/xyz/luan/audioplayers/AudioplayersPlugin.java
- android/src/main/java/xyz/luan/audioplayers/WrappedMediaPlayer.java
- example/lib/main.dart
- example/pubspec.yaml
- lib/audioplayers.dart
As for android media player, it says:
>  Although the asynchronuous seekTo(long, int) call returns right away, the actual seek operation may take a while to finish, especially for audio/video being streamed. When the actual seek operation completes, the internal player engine calls a user supplied OnSeekComplete.onSeekComplete() if an OnSeekCompleteListener has been registered beforehand via setOnSeekCompleteListener(android.media.MediaPlayer.OnSeekCompleteListener).
The background is that, I'm using your plguin to implement some podcast app (thank you for this awesome plugin!). I made a progress bar (listens to `onAudioPositionChanged` stream) and a seek thumb (listens to a stream with combineLatest2 on `onAudioPositionChanged` and a custom stream that's changed on user tab, with the …
> Implement onSeekComplete stream/handler for android

- android/src/main/java/xyz/luan/audioplayers/AudioplayersPlugin.java
I was trying to use this plugin with [audio_service plugin](https://github.com/ryanheise/audio_service) and turns out that it tries to obtain `Activity` object which is unavailable (returns `null`) in background enviroment. Replaced it with `Context`. This allowed registration of plugin inside Android Service to support background playback.
After this change plugin is ready to be used with audio_service plugin which provides support for background playback (it runs Dart code and audio player plugin both in Android service), notification with controls and AudioFocus handling with Dart callbacks. So potentially it can also (partly) resolve following issues: #288, #202, #264.
> Support for registering plugin in background enviroment

- android/src/main/java/xyz/luan/audioplayers/WrappedSoundPool.java
- example/lib/main.dart
- lib/audio_cache.dart
- pubspec.lock
This addresses issue #292 when two or more LOW_LATENCY sounds were loaded concurrently, only the last sound would be playable, the others would be left in a `loading` state. There can only be one `OnLoadCompleteListener` per `SoundPool`. The `SoundPool` variable is static and the `setUrl()` method kept resetting to be the latest instance of `WrappedSoundPool`, so only the latest sound was marked as loaded.
It also address an issue where the playing the same sound repeatedly caused the sound to be loaded again and again. `WrappedSoundPool` now keeps a map of URIs -> sound ids and reuses the sound id when the same URI is played again. `WrappedSoundPool` was confounding the idea of a loaded sound and the playing of a loaded sound. You could not play multiple instances of the same loaded …
> Fix issue #292: Android race condition loading LOW_LATENCY sounds and loading of duplicate sounds

- ios/Classes/AudioplayersPlugin.m
The audio playing by the player will stop other app's music playing background just in iOS.
So int this PR, the `option` parameter is added to the `category` in `AVAudioSession` to make sure the audio and the music playing background will work together.
> add options

- CHANGELOG.md
- example/lib/main.dart
- example/lib/player_widget.dart
- ios/Classes/AudioplayersPlugin.m
- lib/audioplayers.dart
- https://github.com/luanpotter/audioplayers/issues/345
- Fixes #345 by wrapping call to `"audio.onNotificationBackgroundPlayerStateChanged"` in a conditional that is only set by the proper method being called that would ensure that the FlutterEngine has properly registered the handler
- `ios/Classes/AudioplayersPlugin.m`
- Run the example app
-- comment out the call to `_audioPlayer.startHeadlessService();` in `player_widget.dart`
- 😅 been a long time since i had to code **Objective-C** 
- N/A
- https://media.giphy.com/media/39vl0ey26JznsznUHm/giphy.gif
- Tests pass, but no new ones added
> 345 - fix for startHeadlessService() crash

- README.md
There has been an issue causing playing remote urls that are HTTP not to work and after some research, I found out that this is specific to Android only and can be fixed by adding `android:usesCleartextTraffic="true"` in the AndroidManifest.xml file. I figured this info should be included in the docs since there are multiple folks who ran into it as well.
This PR should close out these issues: #375, #369, possibly #181, and #383
> Add documentation about streaming audio from http links

- darwin/Classes/AudioplayersPlugin.m
- This commit implies iOS users _should_ be able to set playback rate prior to playing. Needs testing to be confirmed. Currently here's the docs recommendation on `setPlaybackRate`: [Sets the playback rate - call this after first calling play() or resume().](https://github.com/luanpotter/audioplayers/blob/master/lib/audioplayers.dart#L452)
- Added `playImmediatelyAtRate` to `resume` method with `playbackRate` read from playerInfo's `rate`
- Modified `playImmediatelyAtRate` in `play` method to take `playbackRate` read from playerInfo's `rate` instead of using the constant `_defaultPlaybackRate`
> [iOS] Add `playImmediatelyAtRate` to `resume` and updated `play`

- lib/audioplayers.dart
Initializing parameters does nothing if an app passes the null values.
> Prevent exceptions when null values are passed to notifications center

- darwin/Classes/AudioplayersPlugin.m
currentPlayerId must be assigned in play() and resume() methods, not in setUrl(). This allows apps to use multiple audio players.
With the previous implementation a player which had the last setUrl() call was interacting with the Notifications Center, even if a totally different player was playing at the moment.
Now a correct player interacts with the Notifications Center.
> Fixed logic of assigning currentPlayerId.

- darwin/Classes/AudioplayersPlugin.m
Previously, several callbacks and methods are incorrectly calculating milliseconds from `CMTime` losing fraction of second in the process, i.e. milliseconds that round up to integer seconds and do not retain fraction of second.
This is because `CMTimeGetSeconds(time)` is being cast to `int` instead of `Float64`. The latter retains decimal/precision points.
Added private method `getMillisecondsFromCMTime` that gets accurate integer milliseconds from `CMTime` by using the intermediate type `Float64`.
- `updateDuration` callback (`audio.onDuration`, `onDurationChanged`)
- `getDuration` method
- `getCurrentPosition` method
- `onTimeInterval` callback (i.e. `audio.onCurrentPosition`,  `onAudioPositionChanged`)
For reference, check [this](https://stackoverflow.com/a/6655128/10830091).
> [iOS] Get accurate `milliseconds`

- README.md
- android/src/main/java/xyz/luan/audioplayers/AudioplayersPlugin.java
- android/src/main/java/xyz/luan/audioplayers/Player.java
- android/src/main/java/xyz/luan/audioplayers/WrappedMediaPlayer.java
- android/src/main/java/xyz/luan/audioplayers/WrappedSoundPool.java
- example/lib/player_widget.dart
- lib/audioplayers.dart
Feature to toggle between speakers and earpiece. Can be used to play some thing when no headphones nearby and for not disturbing people around. Switch to headphones if connected (wire and wireless).
1. Added `Content` into a methods `play`, `setUrl` of class `Player`
2. Added `Content` into `setAttributes` of class `WrappedMediaPlayer`
3. Added condition to choose between speakers and earpiece into `setAttributes` of class `WrappedMediaPlayer`
4. Added method `setPlayingRoute` into class `Player`
5. Added implementation of `setPlayingRoute` into `WrappedMediaPlayer`
6. Added new method `handleMethodCall` in to `AudioplayersPlugin` class
7. Added example
Implemented only for Android
- Android v.10 google pixel
- Android v.10 API 29 emulator
- Android v.4.3.1 API 18 emulator
> [Android] Added feature, switch between  speakers and earpiece

- darwin/Classes/AudioplayersPlugin.m
This pull request fixes the restart of a failed AVPlayerItem on iOS
Steps to reproduce (I'm using remote URLs playback):
- play one of the URLs
- turn off the internet connection
- switch to the next URL
- the plugin would correctly report the playback failed
- attempt to restart the playback of the same URL
**Expected result:**
- if the device has the Internet connection, the playback restarts
- if the device has no Internet connection, the error is reported again
**Actual result:**
- nothing happens, the file doesn't play and the error is not reported as well
> Fix restarting the playback of a failed AVPlayerItem on iOS

- CHANGELOG.md
- README.md
- darwin/Classes/AudioplayersPlugin.m
Issue numbers #429 and #389.
Implemented stream routing for iOS. Now able to switch between the main speaker and the earpiece speaker.
> [iOS] switch between speakers and earpiece

- .github/workflows/build.yaml
- .github/workflows/pull-request.yaml
This should fix the build that has been broken for a few days.
> Remove deprecated iOS device from build pipeline

- darwin/Classes/AudioplayersPlugin.m
On my tests with an iPhone 6, using AudioCache, no sound started to play after device was locked. 
Adding this one line fixed it:
```
[[UIApplication sharedApplication] beginReceivingRemoteControlEvents];
```
Hope it can get merged! Thanks a lot for your great work!
> Sound now plays on locked iOS device (fixes #526)

- CHANGELOG.md
- lib/audio_cache.dart
- pubspec.lock
- test/audio_cache_test.dart
This is a breaking change that makes the prefix parameter of audio cache include the assets folder, allowing it to be ovewritten.
> Change prefix to include the assets folder

- android/build.gradle
Fixes the following error when building using `flutter build apk`:
`error: cannot find symbol import androidx.annotation.NonNull;`
> Fixes #614

- lib/audio_cache.dart
In my research, I suspect that the cause is probably that I haven't set `player.setReleaseMode(ReleaseMode.STOP);` before processing player.play in this play method.
So I set the release mode STOP before playing.
This is a bug of the case where `fixedPlayer` is set in `AudioCache`.
I interacted with the developers on the issue page.
https://github.com/luanpotter/audioplayers/issues/618
> added release mode setting to play method.

- darwin/Classes/AudioplayersPlugin.m
https://github.com/luanpotter/audioplayers/blob/3f580954e9ae8b04660ca1c02fdadfa1225888ee/darwin/Classes/AudioplayersPlugin.m#L827
The above line causes this warning to appear in logs:
> [avas]     AVAudioSession_iOS.mm:1150  Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.
The reason is that this is the _shared_ audio session, used by all instances of `AudioPlayer` on the Flutter side. In my app, longer sounds were being interrupted after the completion of shorter sounds played in parallel, and this line was the cause.
This pull request prevents us from deactivating the audio session unless other sounds have finished playing.
> [iOS fix] Do not disable the shared audio session—it breaks multiple players

- CHANGELOG.md
- darwin/Classes/NotificationsHandler.swift
- darwin/Classes/SwiftAudioplayersPlugin.swift
- darwin/Classes/WrappedMediaPlayer.swift
This:
* Extracts the remainder of the notifications code onto the new file, making it more separate than the rest of the code.
* Add more checks and make sure it is not ran on macos or if startHeadlessService is not called, which solves issues like these:
* * https://stackoverflow.com/questions/61263458/flutter-fatal-error-callback-lookup-failed-with-audioplayers-package
* * https://github.com/flame-engine/flame/issues/488
* Unified more of the compile time macros, the less compile time branching we have the better.
> Extract all the notifications code and make it optional

- android/build.gradle
- example/android/build.gradle
Thanks for the great library!
---
fix #718 
- Add `$kotlin_version` and `kotlin-gradle-plugin` at `android/build.gradle`
- Remove stdlib library from dependency block 
- ref <https://kotlinlang.org/docs/reference/whatsnew14.html#dependency-on-the-standard-library-added-by-default>
- Update Kotlin 1.4.21
- <https://github.com/JetBrains/kotlin/releases/tag/v1.4.21>
> Add kotlin-gradle-plugin at android/build.gradle

- android/build.gradle
- android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt
- android/src/main/kotlin/xyz/luan/audioplayers/ByteDataSource.kt
- android/src/main/kotlin/xyz/luan/audioplayers/Player.kt
- android/src/main/kotlin/xyz/luan/audioplayers/WrappedSoundPool.kt
When I checked the android codes to investigate #767 comments, I found some points.
- Add sourceSets to search Kotlin files by Gradle
- Remote unused dependencies
- Optimize imports
> Cleanup gradle file and imports

- darwin/Classes/SwiftAudioplayersPlugin.swift
Hi, I found two code mistakes.
---
The default value of the seek position has changed.
Therefore, it can be played only once.
https://github.com/luanpotter/audioplayers/blob/98281f612f42b351b5cfe94f5dc66e24026d801e/darwin/Classes/SwiftAudioplayersPlugin.swift#L237
https://github.com/luanpotter/audioplayers/blob/cda8c39a01a0e6a0cd53f9c9ba515efc1c518c05/darwin/Classes/AudioplayersPlugin.m#L171
---
The session is not deactivated.
https://github.com/luanpotter/audioplayers/pull/710/files#diff-f48d6c32c3c16cb98ecc2514598b0c3eeff787b78ff213b2aa5960ee647c384cL346-L361
```swift
func maybeDeactivateAudioSession() {
let hasPlaying = players.values.contains { player in player.isPlaying }
if !hasPlaying {
-            setAudioSessionActive(active: false)
-        }
-    }
-    
-    func …
```
> Fix misconfiguration

- android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt
- android/src/main/kotlin/xyz/luan/audioplayers/Player.kt
- android/src/main/kotlin/xyz/luan/audioplayers/WrappedMediaPlayer.kt
Since the dart API is has a non-nullable url string, we can do the same in kotlin.
> Make urls non-nullable on android

- darwin/Classes/WrappedMediaPlayer.swift
This is a fix for https://github.com/luanpotter/audioplayers/issues/801
Skipping forward and back 30 seconds using the in-app controls works well through the seek method:
```dart
_player.seek(_position.inSeconds + 30)
```
However after setting the iOS lock screen controls via:
```dart
_player.setNotification(
title: 'Test Audio',
forwardSkipInterval: Duration(seconds: 30),
backwardSkipInterval: Duration(seconds: 30),
duration: Duration(seconds: duration),
elapsedTime: Duration.zero,
);
```
The lock screen controls move the position forward and backward by **30 milliseconds instead of 30 seconds**.
This simple fix passes the interval as `seconds` instead of `millis`.
> Fix iOS Lockscreen Skip Intervals

- android/build.gradle
Closes https://github.com/luanpotter/audioplayers/issues/790
> Fix Cannot access built-in declaration 'kotlin.String'. Ensure that you have a dependency on the Kotlin standard library

- darwin/Classes/WrappedMediaPlayer.swift
The original fix caused an error by passing the interval as `seconds` - instead we should be passing as `millis` but multiplying by 1000 to achieve the correct skip time.
> iOS Lock Screen Skip Fix Update

- lib/audioplayers.dart
I just ran into a runtime error, when I checked for the state before the player played anything:
```dart
if (player.state == AudioPlayerState.PLAYING) {
player.pause();
} else {
player.resume();
}
```
Was there any reason for `late` to be used for the _audioPlayerState? If not, I think it should be initialized to `STOPPED`.
> Initialize audioPlayerState with STOPPED

- darwin/Classes/NotificationsHandler.swift
- darwin/Classes/SwiftAudioplayersPlugin.swift
- darwin/Classes/Utils.swift
- darwin/Classes/WrappedMediaPlayer.swift
- example/lib/main.dart
- example/lib/player_widget.dart
- lib/audio_cache.dart
- lib/audioplayers.dart
- lib/audioplayers_notifications.dart
- lib/audioplayers_web.dart
- lib/player_mode.dart
- lib/player_state.dart
- lib/playing_route.dart
- lib/release_mode.dart
**Note**: This is a small breaking change.
This is a followup to the first change on the iOS code where the notifications stuff was separated. This does the same on the dart side. I tried to keep this small while at the same time including some improvements.
---
Key changes:
* to avoid circular deps, I had to split the enums from the main audioplayers package. This is a breaking change but an extremely simple one that should not cause any issues. We should probably convert this to the new structure we use at Flame with the `src` folder and group export files, and also divide everything into federated packages, but I did not want to get into that in this PR (cc @renancaraujo).
* The namespace for the notification related methods on the Dart side was changed (for the better IMO).
* I wanna …
> Refactor the Dart side notifications code and extract stuff into files

- CHANGELOG.md
- example/lib/main.dart
- example/pubspec.yaml
- feature_parity_table.md
- lib/audio_cache.dart
- lib/audioplayers_notifications.dart
- pubspec.lock
- pubspec.yaml
- test/audio_cache_test.dart
This is not my ideal implementation. I think in the ideal world we should use playBytes. but I tried looking into that for iOS and seemed very hard. So for now I believe this is a unified way to support all platforms. AFAIK subsequent requests on the browser are cached as expected.
> Implement AudioCache for web

- CHANGELOG.md
- android/src/main/kotlin/xyz/luan/audioplayers/WrappedMediaPlayer.kt
- feature_parity_table.md
This PR re-enables the basic features of AudioPlayers on devices older than API 23
Fixes #829
> Fixing basic features for Android lower than API 23

- CHANGELOG.md
- lib/audio_cache.dart
> Fixing error after playing music several times with AudioCache

- packages/audioplayers/android/build.gradle
- FIX incompatible v1.7.0-alpha.
Please merge and release as a hotfix ASAP as this is a blocking issue. 
This PR fixes #926 and #923
> QUICKFIX Set Kotlin Core to v1.6.0

- README.md
This works on github and on pub.dev
See: 
* https://github.com/dart-lang/pub-dev/issues/4841
* https://github.com/dart-lang/pub-dev/issues/4875
--------
Hint: using symlinks and such is not well supported...
> Fix audio_cache.md link

- packages/audioplayers/android/src/main/kotlin/xyz/luan/audioplayers/WrappedSoundPool.kt
When playing a local file with PlayerMode.LOW_LATENCY, Android passed the path including "file://" to SoundPool, so it was fixed to remove "file://".
> Fixed local file playback in LOW_LATENCY mode on Android

- packages/audioplayers/doc/audio_cache.md
Currently the documentation says it is clearCache to remove everything from cache. But it should be clearAll in the latest version of AudioPlayers.
> "clearCache" is switched to "clearAll" in documentation

- packages/audioplayers/android/src/main/kotlin/xyz/luan/audioplayers/WrappedMediaPlayer.kt
- packages/audioplayers/android/src/main/kotlin/xyz/luan/audioplayers/WrappedSoundPool.kt
fix a bug causing android devices below api < 21 to crash when:
final AudioCache audioCache = AudioCache(prefix: 'assets/audio/');
await audioCache.loadAll([<filenames>]);
audioCache.play(fileName);
> Fix: Fatal exception on Android API < 21 in WrappedMediaPlayer.kt setAttributes

- packages/audioplayers/lib/src/audioplayers_web.dart
Closes #982
please see #982 for why and how this is implemented
> Support `seek` for audioplayers in Flutter Web

- packages/audioplayers/example/lib/main.dart
- packages/audioplayers/example/lib/player_widget.dart
- packages/audioplayers/lib/src/audioplayer.dart
No point in having a named parameter in the setter. Also, the default value is not necessary; changing the playback rate from 1 to 1 changes nothing. If you have something to change it to, provide the value.
> Make setPlaybackRate consistent with other setter methods

- packages/audioplayers/android/build.gradle
- packages/audioplayers/example/android/build.gradle
- packages/audioplayers/example/android/gradle/wrapper/gradle-wrapper.properties
This should fix all the kotlin and agp version incompatibilities peoples
were having.
This updates the AGP version to the latest version which still works
with java 8. Bump gradle version to the minimum required.
Update kotlin to latest 1.4 point release release.
Replace jcenter with mavenCentral as jcenter is scheduled for shutdown.
> update android project files

- .github/workflows/build.yaml
See warning on android tests:
```
Notice: The joschi/setup-jdk GitHub Action is deprecated. Please consider switching to the official actions/setup-java action v2 or later which also supports AdoptOpenJDK and its successor Eclipse Temurin: https://github.com/actions/setup-java/tree/v2.5.0#basic
```
> feat(workflows): replace joschi/setup-jdk, add timeout limits

- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/MediaPlayerPlayer.kt
setDataSource is allowed only in the Idle state per https://developer.android.com/reference/android/media/MediaPlayer#state-diagram
the only way to get into the idle state is by calling reset(), which is also safe to do in idle state
> reset before setting source in MediaPlayer

- packages/audioplayers/example/ios/Podfile.lock
- packages/audioplayers_darwin/darwin/Classes/WrappedMediaPlayer.swift
This makes sure that subsequent `play` calls with the same audio (or simply `resume`) with restart after completion.
> fix: Make sure onComplete resets the position even when not looping

- packages/audioplayers_web/lib/wrapped_player.dart
If playing streams on web, the duration is an infinite number, which was not considered in the implementation. Therefore it throwed an error: `Unsupported operation: Infinity`
> fix(web): handle infinite duration

- packages/audioplayers/example/macos/Podfile.lock
- packages/audioplayers_darwin/darwin/Classes/WrappedMediaPlayer.swift
This issue was noted by @Gustl22 on https://github.com/bluefireteam/audioplayers/pull/1128
Unlike other platforms, on iOS rn if `setSourceUrl` is called, the audio then immediatly starts playing after loading. This was because calling set volume / set playback rate actually triggers the audio to start on iOS.
So this:
* only calls configurePlayer during setSource when isPlaying is true
* call configurePlayer on resume
There is also another issue with the test which is the fact that we are not listening for the duration stream on the sources tab. on ios, the duration update when `setSource` happens way too quickly, so when the test switches to the streams tab, the duration stream is not set. So I made it fire _again_ when resume is called. I think that is not a problem. The duration should …
> fix: ios/macos no longer start audio when calling only setSourceUrl

- packages/audioplayers_linux/linux/audio_player.cc
Position event is only triggered after an interval (here 1s), now it's triggered once immediately when start playing.
Tests follow in #1214 
> fix(linux): emit position event immediately when resume

- .github/workflows/build.yaml
- packages/audioplayers/example/integration_test/app_test.dart
- packages/audioplayers/example/integration_test/test_utils.dart
- packages/audioplayers/example/lib/components/player_widget.dart
- ~Not yet fixed explicitely: TimeoutException for [this](https://github.com/bluefireteam/audioplayers/runs/7283092349?check_suite_focus=true).~ But may not occur anymore due to better performance of emulator. Or if it reoccurs error logging is improved to better estimate the values
> chore: Make tests less flaky

- packages/audioplayers_windows/windows/audio_player.cpp
- packages/audioplayers_windows/windows/audio_player.h
`onDuration` currently only was sent, when source is initialized. Now its also updated, when playing / resuming, so it's consistent with the other platform implementations.
Tests follow in #1238
Closes #1233
> fix(windows): send onDuration event when play/resume

- packages/audioplayers_web/lib/wrapped_player.dart
Web: When hitting stop or the player completed playing the source the position remained at the current one. Now it's reset to 0, like on the other platforms.
The tests follow in #1238
> fix(web): reset position, when stop or playing ended

- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt
Low Latency mode does not work on Android.
I think fix #1193 problem.
Here is sample code.
Work fine
```dart
final file = AssetSource("sounds/sound.mp3");
final player = AudioPlayer();
player.setPlayerMode(PlayerMode.lowLatency);
player.play(file);
```
Does not work
```dart
final file = AssetSource("sounds/sound.mp3");
final player = AudioPlayer();
await player.setPlayerMode(PlayerMode.lowLatency);
player.play(file);
```
Does not work
```dart
final file = AssetSource("sounds/sound.mp3");
final player = AudioPlayer();
player.play(file, mode: PlayerMode.lowLatency);
```
fixes #1193
> fix: Fix lowLatency mode not working on Android (#1193)

- packages/audioplayers_windows/windows/audio_player.cpp
This pull request makes audio playback not depend on file extension on Windows by adding the [`MF_RESOLUTION_CONTENT_DOES_NOT_HAVE_TO_MATCH_EXTENSION_OR_MIME_TYPE`][source-resolver-flags] flag.
Before this pr, the file extension of an audio file must be correct. However, it's common that file extension mismatches, or for cached audio files which may not have an extension.
I'm not sure whether this should be a feature or bug fix. On macOS, the player expects whatever extension for playback, but the extension must exist.
[source-resolver-flags]: https://docs.microsoft.com/en-us/windows/win32/medfound/source-resolver-flags
[Contributor Guide]: https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#feature-re …
> feat: select decoder automatically on windows

- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt
Android: emits onPositionChanged  event, when seek is completed.
Closes #1259 
> fix(android): emit onPositionChanged when seek is completed (closes #1259)

- feature_parity_table.md
- packages/audioplayers_web/lib/wrapped_player.dart
* emit duration if start playing
* emit seek completed event
* avoid resetting player if pausing in release mode
- Enable seek and duration events in web implementation.
- Fix bug, where player is reset to null on pause in release mode.
Closes #1023 
> fix(web): bugs from integration tests

- packages/audioplayers_android/android/build.gradle
Revert compileSdkVersion to not have a warning during execution, when using sdk <=31.
See #1263
> fix(android): revert compileSdkVersion to be compatible with flutter.compileSdkVersion

- packages/audioplayers/lib/src/audioplayer.dart
- packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart
This is regression introduced in 1.0.0.
In 0.2.0, this logic was:
```dart
case 'audio.onComplete':
player.state = PlayerState.COMPLETED;
player._completionController.add(null);
```
So along with the completionController stream being update, the state was set to completed. 
In 1.0.0 there is no such functionality:
```dart
case 'audio.onComplete':
emitComplete(playerId);
```
Since `audioplayers_platform_interface` package doesn't have a reference to `player.state` anymore because it's now in `audioplayers` package, my fix consisted of simply listening to this same stream in `audioplayers` package and updating the state.
I'm not sure how to test this properly.
Closes #1242
> fix: player state not being updated to completed

- packages/audioplayers_web/lib/audioplayers_web.dart
- packages/audioplayers_web/lib/num_extension.dart
- packages/audioplayers_web/lib/util.dart
- packages/audioplayers_web/lib/wrapped_player.dart
Like on #1192, if calling `getDuration` an infinite value is returned, which isn't handled by the web implementation.
> fix(web): handle infinite value on getDuration for live streams

- packages/audioplayers/example/ios/Podfile.lock
- packages/audioplayers/example/ios/Runner.xcodeproj/project.pbxproj
- packages/audioplayers/example/macos/Podfile.lock
- packages/audioplayers_darwin/darwin/Classes/Utils.swift
I decided to do a separate PR, as it doesn't really belong to the tests in #1284.
Avoid getting error when calling `getDuration` on darwin, when getting back infinity or NaN values.
Closes #1024
Tests follow in #1284 
> fix(darwin): infinity / nan on getDuration

- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt
When playing a lot of sounds simultaneously apparently some users get `ConcurrentModificationException` in this for loop.
The best solution would be to be able to use a `ConcurrentHashMap`, but I don't know how to do that in here.
Closes #1274 
> fix(android): Avoid ConcurrentModificationException

- feature_parity_table.md
- packages/audioplayers/example/integration_test/platform_features.dart
- packages/audioplayers_web/lib/web_audio_js.dart
- packages/audioplayers_web/lib/wrapped_player.dart
- packages/audioplayers_web/pubspec.yaml
Co-authored-by: Andrew Novikov <89590481+novikov-studio@users.noreply.github.com>
See #58
Template:
https://mdn.github.io/webaudio-examples/stereo-panner-node/
See #1248 
> feat(web): add setBalance (#58)

- packages/audioplayers_linux/linux/audio_player.cc
- packages/audioplayers_linux/linux/audio_player.h
Sometimes sound is not played, if setting the source for the player and immediately start it (like the `play` method).
So now it starts playing as soon as the sound is initialized, if the user already decided to play the source (similar to Android).
Possible fix for: #1144 
> fix(linux): play sound, when initialized

- packages/audioplayers/lib/src/source.dart
Log paths or url of sources, if calling the `toString()` method. This is especially useful for debugging.
> feat: log path or url of sources

- packages/audioplayers/example/integration_test/tabs/stream_tab.dart
- packages/audioplayers_windows/windows/MediaFoundationHelpers.h
Fixes the precision of `seek`, `getCurrentPosition`, `getDuration` and their streams on windows. Currently, due to a casting bug, the precision is 1 second.
None
> fix: Duration precision on Windows

- README.md
- packages/audioplayers/pubspec.yaml
- packages/audioplayers_android/pubspec.yaml
- packages/audioplayers_darwin/pubspec.yaml
- packages/audioplayers_linux/pubspec.yaml
- packages/audioplayers_platform_interface/pubspec.yaml
- packages/audioplayers_web/pubspec.yaml
- packages/audioplayers_windows/pubspec.yaml
- troubleshooting.md
As pointed out to me by boraizzet, if you go to our [pub page](https://pub.dev/packages/audioplayers/example), this link is broken:
Because it assumes the code is in the root of the repo (`https://github.com/luanpotter/audioplayers/blob/master/example/lib/main.dart`). That is controlled by the `repository` entry on pubpsec, which we don't even have -- so i falls back to `homepage`.
So this PR fixes a few issues with our pubspec setup regarding the repo:
* fixes the old repo url to the new bluefire one
* add both homepage and repository as they are different things
* homepage still points to the root of the repo for the nice readme -- for now
* repository points to the actually repository folder inside the `blob/master`
This is in line with how other mono-repos do it, [for example …
> docs: Fix repos and homepages on pubspecs

- packages/audioplayers/example/integration_test/tabs/controls_tab.dart
- packages/audioplayers/example/integration_test/tabs/source_tab.dart
- packages/audioplayers/example/integration_test/tabs/stream_tab.dart
- packages/audioplayers/example/integration_test/test_utils.dart
- packages/audioplayers/example/lib/tabs/streams.dart
- packages/audioplayers/lib/src/audioplayer.dart
- packages/audioplayers/test/audioplayers_test.dart
Provide a way to get the current source. Theoretically the developer could save the source in its own variable, what they most probably currently do. But this is tended to be error prone. This change would provide an easy access to the current source which also considers the `release / release mode` functionality.
This change would also be necessary to provide better logs from the library side. 
> feat: get current source

- packages/audioplayers/example/lib/components/btn.dart
- packages/audioplayers/example/lib/components/cbx.dart
- packages/audioplayers/example/lib/components/dlg.dart
- packages/audioplayers/example/lib/components/pad.dart
- packages/audioplayers/example/lib/components/player_widget.dart
- packages/audioplayers/example/lib/components/tab_wrapper.dart
- packages/audioplayers/example/lib/components/tabs.dart
- packages/audioplayers/example/lib/components/tgl.dart
- packages/audioplayers/example/lib/components/txt.dart
- packages/audioplayers/example/lib/main.dart
- packages/audioplayers/example/lib/tabs/audio_context.dart
- packages/audioplayers/example/lib/tabs/controls.dart
- packages/audioplayers/example/lib/tabs/logger.dart
- packages/audioplayers/example/lib/tabs/sources.dart
- packages/audioplayers/example/lib/tabs/streams.dart
- packages/audioplayers/example/pubspec.yaml
Support for super initializers.
Upgrade Flutter to use more readable super initializersand have less boilerplate code.
> feat: upgrade Flutter to v3.0.0 and Dart 2.17 in example

- packages/audioplayers/example/lib/tabs/audio_context.dart
- packages/audioplayers_darwin/ios/Classes/AudioContext.swift
- packages/audioplayers_platform_interface/lib/api/audio_context_config.dart
- The parameter `defaultToSpeaker` was not used in `AudioContextIOS`. Instead `option: [AVAudioSessionOptions.defaultToSpeaker]` should be used
- `AudioContext` now has default configurations for `iOS` and `android`. Nevertheless it is recommended to set the config via `AudioContextConfig.build()`.
Old: 
```dart
AudioPlayer.global.setGlobalAudioContext(
AudioContext(
iOS: AudioContextIOS(
defaultToSpeaker: true,
category: AVAudioSessionCategory.playback,
options: [AVAudioSessionOptions.mixWithOthers],
),
android: AudioContextAndroid(
isSpeakerphoneOn: true,
stayAwake: true,
contentType: AndroidContentType.music,
usageType: AndroidUsageType.media,
audioFocus: AndroidAudioFocus.gain,
),
),
);
```
New:
```dart
AudioPlayer.global.setGlobalAudioContext(
AudioContext(
iOS: AudioContextIOS( …
```
> fix!: remove unused `defaultToSpeaker` in `AudioContextIOS` and replace with `AVAudioSessionOptions.defaultToSpeaker`

- packages/audioplayers_web/lib/web_audio_js.dart
This PR fixed a build error described here: https://github.com/bluefireteam/audioplayers/issues/1378
It changes all `external ...` with `external factory` in packages/audioplayers_web/lib/web_audio_js.dart, as described in this issue https://github.com/flutter/flutter/issues/115988
Note: only minor changes that don't require updating tests, docs or example
Fixes #1378
> fix(web): Error: "@staticInterop" classes should not contain any generative constructors

- packages/audioplayers/example/lib/main.dart
> feat(example): add and remove player actions

- packages/audioplayers_darwin/ios/Classes/AudioContext.swift
I haven't tried this on a real device so it's quite a shot in the dark.
Closes #1194 
> fix(iOS): Default to speaker instead of earpiece on iOS

- packages/audioplayers/example/integration_test/lib_test.dart
- packages/audioplayers/example/integration_test/tabs/context_tab.dart
- packages/audioplayers/example/integration_test/tabs/controls_tab.dart
- packages/audioplayers/example/integration_test/tabs/logs_tab.dart
- packages/audioplayers/example/integration_test/tabs/properties.dart
- packages/audioplayers/example/integration_test/tabs/source_tab.dart
- packages/audioplayers/example/integration_test/tabs/stream_tab.dart
- packages/audioplayers/example/integration_test/test_utils.dart
The CI sometimes fails, but it is hard to determine, what actually causes the long processing. So let's print some time stamps.
> test: print times on failure, increase timeout for PlayerState.completed

- packages/audioplayers/LICENSE
- packages/audioplayers_android/LICENSE
- packages/audioplayers_darwin/LICENSE
- packages/audioplayers_linux/LICENSE
- packages/audioplayers_platform_interface/LICENSE
- packages/audioplayers_web/LICENSE
- packages/audioplayers_windows/LICENSE
Since you can't publish a package with a symlink referring outside of the package this turns all the LICENSE symlinks to real files.
> chore: Use license file directly instead of symlinks

- feature_parity_table.md
- packages/audioplayers/example/integration_test/platform_features.dart
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/MediaPlayerPlayer.kt
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/Player.kt
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/SoundPoolPlayer.kt
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/WrappedPlayer.kt
Set balance for Android. Takes in proposals of #1413.
#58
> feat(android): add `setBalance` (#58)

- packages/audioplayers/example/integration_test/platform_features.dart
- packages/audioplayers/example/integration_test/tabs/stream_tab.dart
- packages/audioplayers_platform_interface/lib/src/api/audio_context.dart
- packages/audioplayers_platform_interface/lib/src/api/audio_context_config.dart
[Flutter recommends](https://api.flutter.dev/flutter/foundation/defaultTargetPlatform.html) using `defaultTargetPlatform` instead of `Platform.isX`, where possible. This also enables testing platform specific dart code in unit tests (but without native code), which is way more convenient and faster.
> feat: replace `Platform.isX` with `defaultTargetPlatform`

- getting_started.md
- packages/audioplayers_linux/setup.md
- packages/audioplayers_windows/setup.md
- packages/audioplayers_windows/windows/CMakeLists.txt
- troubleshooting.md
The standard cmake message command prints to `stderr`. So it prints `Nuget.exe not found, trying to download or use cached version.`, when building an audioplayers app, which is confusing, as nothing went wrong. The `STATUS` keyword changes it to `stdout`, which can be accessed via the `flutter --verbose` command.
Also: 
- updated the `nuget` package to `v6.5.0`
- updated the docs on how to setup Windows and Linux. The paths could change again, once there are individual READMEs for each platform.
#1319
#1114
Closes #1303
> feat(windows): show nuget download info explicitely in verbose mode

- packages/audioplayers/test/audioplayers_test.dart
- packages/audioplayers/test/global_audioplayers_test.dart
- packages/audioplayers_platform_interface/test/audioplayers_platform_test.dart
- packages/audioplayers_platform_interface/test/global_platform_test.dart
Sometimes the tests fail, because the events are emitted after the event tests are finished. This awaits the controller to prevent such behavior.
_I could not reproduce locally, but I'm quite sure this is the reason._
See https://github.com/bluefireteam/audioplayers/actions/runs/4606766296/jobs/8140467339
> test: fix await closing event controller

- packages/audioplayers/example/.metadata
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt
Unlike on other platforms, onDuration is constantly called on Android. This PR avoids calling onDuration on every position event.
OnDuration is still once called with the correct duration after having prepared the source.
Closes #136
> fix(android): Avoid calling onDuration on position event (closes #136)

- .github/workflows/pull-request.yml
- melos.yaml
- packages/audioplayers/lib/src/audio_cache.dart
- packages/audioplayers/pubspec.yaml
- packages/audioplayers/test/audio_cache_test.dart
- packages/audioplayers/test/audio_pool_test.dart
- packages/audioplayers/test/audioplayers_test.dart
- packages/audioplayers/test/global_audioplayers_test.dart
- packages/audioplayers_platform_interface/test/audioplayers_platform_test.dart
- packages/audioplayers_platform_interface/test/global_platform_test.dart
- test: await AudioCache operations
- feat: mock FileSystem in AudioCache, to be able to test without platforms
- fix ConcurrentModificationException in `AudioCache().clearAll()`
- ci: execute platform independent tests in Draft mode
Reason for the mocks:
When clearing the files, at least on Windows the tests failed, as the file system could not find these files. As so it should have failed in Linux, too, don't know why it didn't fail on the CI for so long, but that's maybe the reason, why it fails now sometimes. Probably the clear command failed, but wasn't necessary for the test to succeed, as it was not awaited.
> test: mock `FileSystem`, fix awaits, fix ConcurrentModificationException

- getting_started.md
The estimated link for the dart docs, didn't work out for the release, so changed it to https://pub.dev/documentation/audioplayers/latest/audioplayers/AudioContextConfig-class.html
See #1442
> docs: Update AudioContextConfig link to docs

- packages/audioplayers/example/integration_test/lib_test.dart
- packages/audioplayers/example/lib/main.dart
- packages/audioplayers/lib/src/audioplayer.dart
- packages/audioplayers/test/audioplayers_test.dart
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt
- packages/audioplayers_darwin/darwin/Classes/SwiftAudioplayersDarwinPlugin.swift
- packages/audioplayers_linux/linux/audioplayers_linux_plugin.cc
- packages/audioplayers_web/lib/audioplayers_web.dart
- packages/audioplayers_windows/windows/audioplayers_windows_plugin.cpp
The implementation to dispose a player on the native side was missing for many platforms.
See https://github.com/bluefireteam/audioplayers/issues/1467#issuecomment-1503685651
> fix: dispose player implementation

- packages/audioplayers_web/lib/wrapped_player.dart
Setting `currentTime` of `AudioElement` after calling `play` can cause a stutter, if the browser is able to start playback of the audio immediately and execution after `play` is delayed by other tasks in the event loop.
By setting `currentTime` before calling `play` this issue can be avoided.
> fix(web): Avoid stutter when starting playback

- .github/workflows/build-example.yml
- .github/workflows/test.yml
- Use Github Runner image `macos-13` for Integration tests (Closes #1405)
- Remove unnecessary actions
> ci: fix macos integration tests, remove unnecessary actions

- .github/workflows/test.yml
- getting_started.md
- packages/audioplayers/example/integration_test/lib_test.dart
- packages/audioplayers/lib/src/audio_pool.dart
- packages/audioplayers/lib/src/audioplayer.dart
- packages/audioplayers/test/audioplayers_test.dart
- packages/audioplayers/test/fake_audioplayers_platform.dart
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/WrappedPlayer.kt
- packages/audioplayers_darwin/darwin/Classes/SwiftAudioplayersDarwinPlugin.swift
- packages/audioplayers_darwin/darwin/Classes/WrappedMediaPlayer.swift
- packages/audioplayers_linux/linux/audio_player.cc
- packages/audioplayers_linux/linux/audio_player.h
- packages/audioplayers_linux/linux/audioplayers_linux_plugin.cc
- packages/audioplayers_platform_interface/lib/src/api/player_state.dart
- packages/audioplayers_web/lib/audioplayers_web.dart
- packages/audioplayers_windows/windows/audioplayers_windows_plugin.cpp
- Add `PlayerState.disposed` (closes #1450)
- Add `AudioPool.dispose()` (closes #1478)
- Dispose players in tests
- Properly handle dispose on all platforms (closes #1475)
- Fix running method calls on non UI threads causes PlatformException (closes #1481)
Closes #1450 
Closes #1478 
Closes #1475 
Closes #1481
> fix: rework dispose

- packages/audioplayers/example/integration_test/tabs/stream_tab.dart
- packages/audioplayers_darwin/darwin/Classes/WrappedMediaPlayer.swift
- packages/audioplayers_linux/linux/audio_player.cc
- packages/audioplayers_web/lib/num_extension.dart
- Linux: changed update interval from `1000ms` to `250ms`
- Web: `position` was rounded to `1s` as its handed over as float, now it's multiplied with `1000` to profit from millisecond precision, update interval is still dependent on browser implementation
- Darwin: changed update interval from `0.2ms` to `200ms`, which most probably was a mistake and caused much overhead
> feat: Adapt position update interval of darwin, linux, web 

- .github/workflows/build-example.yml
- .github/workflows/test.yml
Like in [flame](https://github.com/flame-engine/flame/blob/19d1e72e4bb51550752b346525e51be67edc2019/.github/workflows/cicd.yml#L18) it is more practicable to use fixed version of `flutter-action` to avoid unexpected failures of the CI. 
Further when flutter is releasing a new version, one should upgrade the version of `flutter-action` and also add the required changes to pass the tests at the same time. 
This ensures that the tests in the main always stay consistent. It also makes the development faster and more independent of other packages such as `flame-lint`.
https://github.com/flame-engine/flame/pull/2532
[Contributor Guide]: https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#feature-requests--pr …
> ci: Use fixed version of flutter-action

- packages/audioplayers_platform_interface/lib/src/api/audio_context_config.dart
Improves documentation for `AudioContextConfig.respectSilence`. It should now be easier to understand what it does.
Fixes #1490.
> docs: Improve doc for 'AudioContextConfig.respectSilence' (#1490)

- packages/audioplayers_android/android/build.gradle
- packages/audioplayers_android/android/src/main/AndroidManifest.xml
Cherry-pick of #1503
You can upgrade your Android project to use AGP 8. In your `android/build.gradle` :
```gradle
buildscript {
// ...
dependencies {
classpath 'com.android.tools.build:gradle:8.0.1'
// ...
}
}
```
If doing so, also don't forget to add a namespace in the `android` section of `android/app/build.gradle` :
```gradle
android {
// ...
namespace 'your.namespace'
}
```
Then can also remove the `package` property in your `android/app/src/main/AndroidManifest.xml`
#1503 
[example]: https://github.com/bluefireteam/audioplayers/tree/main/packages/au …
> fix(android): Add AGP 8 support with namespace property

- packages/audioplayers_platform_interface/lib/src/api/audio_event.dart
> fix: AudioEvent missing `isPrepared`

- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt
Close #1522 
I am not sure whether this is the best way, but I can confirm it fixes the bug I see, and IMHO there are not infinitely many handler callbacks, so skipping this cancelation does not cause harm.
> fix(android): `onPlayerStateChanged` is not called when audio has completed playing

- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/AudioContext.kt
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/FocusManager.kt
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/WrappedPlayer.kt
- packages/audioplayers_platform_interface/lib/src/api/audio_context.dart
- fix(android): allow AudioFocus.none (closes #1495)
- refactor: values for AudioContext enums
Closes #1495
Closes #1534
> fix(android): Allow AudioFocus.none

- packages/audioplayers/example/android/build.gradle
Just as the after gradle build the file is changed to this definition. Seems to have happened on gradle or flutter update.
> chore(android): update `task clean()` to `tasks.register("clean")`

- packages/audioplayers/example/integration_test/lib_test.dart
- packages/audioplayers/example/lib/tabs/audio_context.dart
- packages/audioplayers/test/global_audioplayers_test.dart
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/AudioContext.kt
- packages/audioplayers_darwin/ios/Classes/AudioContext.swift
- packages/audioplayers_platform_interface/lib/src/api/audio_context.dart
- packages/audioplayers_platform_interface/lib/src/api/audio_context_config.dart
- packages/audioplayers_platform_interface/test/global_platform_test.dart
Supersedes #1501
* Introduce `AudioContextConfigRoute` to allow forcing audio to `speaker` or `earpiece` (this can be extended to e.g. bluetooth devices) for both iOS and Android
* ios: change default AVAudioSessionCategory from `.playAndRecord` to `.playback` to not play from earpiece as in record mode (see #1194)
* ios: remove default `AVAudioSessionOptions.defaultToSpeaker` to allow playing from system default device instead of speaker only (see #1486)
* android: change default AudioContextAndroid.isSpeakerphoneOn from `true` to `false` to allow playing from system default device instead of speaker only (see #1486)
* ios: remove default `AVAudioSessionOptions.mixWithOthers` to interrupt audio of other apps, like in Android
* android: change default AudioContextAndroid.stayAwake from …
> fix!:  Default audio output to system preferences

- packages/audioplayers/example/android/build.gradle
Use kotlin version which is compatible with AGP8.
See https://github.com/bluefireteam/audioplayers/actions/runs/5616959780/job/15220225951 :
```
e: /home/runner/work/audioplayers/audioplayers/packages/audioplayers/example/build/audioplayers_android/.transforms/b8ec2b7f9edecdc552d5b724ef88efef/transformed/out/jars/classes.jar!/META-INF/audioplayers_android_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.0/8ee15ef0c67dc83d874f412d84378d7f0eb50b63/kotlin-stdlib-1.9.0.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its …
```
> fix(example): Use kotlin version compatible with AGP8

- packages/audioplayers_android/android/build.gradle
Revert the update of `androidx.core:core-ktx` version from `1.9.0` to `1.10.1` in #1577. The update was originally proposed by the IDE, but this requires AGP 8 to be used.
Closes #1588
I thought I tested this, but obviously I did not.
#1577
> revert(android): Upgrade androidx.core:core-ktx, restore support for AGP7

- packages/audioplayers/example/ios/Podfile.lock
- packages/audioplayers/example/ios/Runner.xcodeproj/project.pbxproj
- packages/audioplayers/example/macos/Podfile.lock
- packages/audioplayers_darwin/darwin/Classes/SwiftAudioplayersDarwinPlugin.swift
- packages/audioplayers_darwin/darwin/Classes/WrappedMediaPlayer.swift
- packages/audioplayers_darwin/macos/Classes/AudioContext.swift
Pick refactor code of #1549 
#1549 
> refactor(darwin): Rearrange code

- .github/workflows/test.yml
Introduced in #1570. It seems that `Set-Data` in powershell not reliably is setting the time, or the system is not triggered to set the time. Probably a call to `Get-Time` triggers the system to update the time.
But this is just a theory. Anyways I ran multiple attempts, and in this PR this seems fixing the issue. I validated by enabling the timestamps in the GH runs.
> ci(windows): Attempt to fix flakiness in setting windows time

- .github/workflows/test.yml
- packages/audioplayers_platform_interface/lib/src/audioplayers_platform.dart
- packages/audioplayers_platform_interface/test/audioplayers_platform_test.dart
- packages/audioplayers_platform_interface/test/global_platform_test.dart
- packages/audioplayers_platform_interface/test/util.dart
Currently if an event stream for a `playerId` is requested, a new stream was created, conflicting with the existing one. Now the `createEventStream`, `disposeEventStream` and `getEventStream` methods allow more control of handling the stream and also reusing the existing stream on `getEventStream`. 
Info: this wasn't a problem so far, as one AudioPlayer only held one instance of an event stream. But this is problematic on requesting the stream multiple times on different levels in the tests.
[example]: …
> feat: create, dispose & reuse event stream

- packages/audioplayers/example/lib/tabs/audio_context.dart
- packages/audioplayers/example/lib/utils.dart
- packages/audioplayers_platform_interface/lib/src/api/audio_context_config.dart
- packages/audioplayers_platform_interface/test/audio_context_test.dart
- Improve assertion error messages for `AudioContextConfig` for values set on iOS
- Fix example, as it could and should not alternate the `options` array for AudioContextIOS
- Improve example to show assertion errors as toast to the user
> feat(ios): Improved AudioContextConfig assertions, fix example

- .github/workflows/test.yml
- If PR comes from a foreign repository the repo has to be checked out completely for super-linter.
- Also use slim image to reduce CI time
#1610 
> ci: Fix checkout for super-linter, use slim image

- packages/audioplayers/example/integration_test/platform_test.dart
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/MediaPlayerPlayer.kt
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/WrappedPlayer.kt
- packages/audioplayers_darwin/darwin/Classes/WrappedMediaPlayer.swift
> fix: Set playback rate only when playing

- getting_started.md
- packages/audioplayers/example/integration_test/app/app_test_utils.dart
- packages/audioplayers/example/integration_test/app/tabs/controls_tab.dart
- packages/audioplayers/example/integration_test/app/tabs/stream_tab.dart
- packages/audioplayers/example/integration_test/lib/lib_test_utils.dart
- packages/audioplayers/example/integration_test/lib_test.dart
- packages/audioplayers/example/integration_test/platform_features.dart
- packages/audioplayers/example/integration_test/platform_test.dart
- packages/audioplayers/lib/audioplayers.dart
- packages/audioplayers/lib/src/audioplayer.dart
- packages/audioplayers/lib/src/position_updater.dart
- packages/audioplayers/test/audioplayers_test.dart
- packages/audioplayers/test/fake_audioplayers_platform.dart
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/MediaPlayerPlayer.kt
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/Player.kt
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/SoundPoolPlayer.kt
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/WrappedPlayer.kt
- packages/audioplayers_darwin/darwin/Classes/SwiftAudioplayersDarwinPlugin.swift
- packages/audioplayers_darwin/darwin/Classes/WrappedMediaPlayer.swift
- packages/audioplayers_linux/linux/audio_player.cc
- packages/audioplayers_linux/linux/audio_player.h
- packages/audioplayers_platform_interface/lib/src/api/audio_event.dart
- packages/audioplayers_platform_interface/lib/src/audioplayers_platform.dart
- packages/audioplayers_platform_interface/test/audioplayers_platform_test.dart
- packages/audioplayers_web/lib/wrapped_player.dart
- packages/audioplayers_windows/windows/MediaEngineWrapper.cpp
- packages/audioplayers_windows/windows/MediaEngineWrapper.h
- packages/audioplayers_windows/windows/audio_player.cpp
- packages/audioplayers_windows/windows/audio_player.h
- Make the position stream updates configurable via `PositionUpdater`:
- By default the position stream is updated on every new frame with help of `FramePositionUpdater`.
- If setting the `AudioPlayer.positionUpdater` to `TimerPositionUpdater` , the position stream is updated in the according interval.
- The execution on the separate IO thread on Android was moved to the relevant code part in `SoundPoolPlayer`.
If the PR is a breaking change this should be indicated with suffix "!" 
(for example, `feat!:`, `fix!:`). See [Conventional Commit] for details. -->
Removed in `audioplayers_platform_interface`:
```
AudioEventType.position
AudioEvent.position
```
Closes #349
Closes #1525 …
> feat!: FramePositionUpdater & TimerPositionUpdater

- packages/audioplayers/lib/src/audioplayer.dart
This PR is fixing the bug in which in web while initialising the play with duration specified, there was no seek happening, which means that it starts from the beginning itself. setting the source before calling seek in play() function, instead of setting it afterwards solves the issue, bec the AudioElement instance _player in wrappedPlayer class should be initailised before seeking.
Closes #1597
[issue database]: https://github.com/https://github.com/bluefireteam/audioplayers/issues/1597
> fix: Seek not applied in `play` method

- packages/audioplayers/example/integration_test/lib_test.dart
- packages/audioplayers/example/windows/flutter/CMakeLists.txt
- packages/audioplayers/lib/src/audioplayer.dart
Fixes #1687
Instead we could also set the state always at the beginning of each method, but this raises these problems:
- If the operation in the method throws an error, the state doesn't match the native players state
- The state doesn't reflect the current real world audio state, as it's maybe still preparing/buffering and not actually playing
#1687
> fix: Race condition when playing/pausing audio

- getting_started.md
- packages/audioplayers/example/README.md
- packages/audioplayers/example/example.dart
- packages/audioplayers/example/example.md
- packages/audioplayers/example/lib/components/player_widget.dart
- packages/audioplayers/example/lib/tabs/sources.dart
- packages/audioplayers_platform_interface/lib/src/api/player_mode.dart
- troubleshooting.md
Improve the documentation for:
- Getting started: 
- Fix typos from #1678
- Call stop in low latency, missing completion event (#1489)
- Set prefix for AssetSource via AudioCache (#1620, #1639)
- Troubleshooting guide:
- Verify audio format, e.g. with Aconvert
- Change heading size of web-cors-policy
- Example:
- README: How to setup example with `melos`, tab descriptions
- example.md: Add Simple (one-page) Example for pub.dev, see https://dart.dev/tools/pub/package-layout#examples (#1616)
- Showcase for using play in `addPostFrameCallback`
See #1650 
#1650 …
> docs: Improve Docs

- .github/workflows/build-example.yml
- .github/workflows/test.yml
Setup-cocoapods is used to install the according version before building. But this is not necessarily needed, as a higher installation should still be able to execute macos apps with pods lower than described in the podfile.lock.
The package setup-cocoapods action includes a [bug]( https://github.com/maxim-lobanov/setup-cocoapods/pull/28) which let fail the CI from time to time. Flutter Gallery also doesn't setup the [cocoapod executable](https://github.com/flutter/gallery/blob/main/.github/workflows/build.yml).
[example]: …
> ci: Remove setup-cocoapods on macos builds

- packages/audioplayers/example/example.md
- packages/audioplayers/example/integration_test/lib_test.dart
- packages/audioplayers/example/lib/components/player_widget.dart
- packages/audioplayers/lib/src/audioplayer.dart
- packages/audioplayers_linux/linux/audio_player.cc
- packages/audioplayers_linux/linux/audio_player.h
- packages/audioplayers_linux/linux/audioplayers_linux_plugin.cc
Wait for seek to finish by listening to the `AudioEventType.seekComplete` event.
> fix: Wait for seek to complete

- packages/audioplayers/example/lib/tabs/audio_context.dart
- packages/audioplayers_platform_interface/lib/src/api/audio_context_config.dart
- packages/audioplayers_platform_interface/test/audio_context_test.dart
- Introduces `AudioContextConfigFocus.mixWithOthers` to unify `AVAudioSessionOptions.mixWithOthers` (iOS) and `AndroidAudioFocus.none` (Android)
- Replaces the option `AudioContextConfig.duckAudio = true` with `AudioContextConfig.focus = AudioContextConfigFocus.duckOthers`
Closes #1718
Before:
```dart
AudioContextConfig(
duckAudio: true,
);
```
After:
```dart
AudioContextConfig(
focus: AudioContextConfigFocus.duckOthers,
);
```
Closes #1718
[example]: https://github.com/bluefireteam/audioplayers/tree/main/packages/a …
> feat!: Extend `AudioContextConfig.duckAudio` to `AudioContextConfig.focus`

- packages/audioplayers_linux/linux/audio_player.cc
Failures which occured in OnMediaStateChange method, were also thrown in OnMediaError. So the error was propagated twice and therefore the tests fail from time to time. This ensures to correctly throw the error only once, but also log the state change failure.
The tests should already cover this, but succeeded anyways. This should change after #1715. 
#1715
> fix(linux): Handle failures of OnMediaStateChange in OnMediaError

- packages/audioplayers/example/integration_test/platform_test.dart
- packages/audioplayers/lib/src/audioplayer.dart
Wait simultaneously for async calls (Futures and Streams) to ensure all errors are propagated through one common future. Previously a stream could throw an error before it was even listened to, as the process still awaited an async call (here `setSource`).
The tests are adapted, but not explicitly written to avoid that error. But the error would occur since Flutter 3.16.x, so they are tested against in #1715 without further ado.
#1715
[example]: https://github.com/bluefireteam/audioplayers/tree/main/packages/audiopl …
> fix: Propagate Stream Errors through the same Future

- packages/audioplayers/lib/src/audio_cache.dart
- packages/audioplayers/test/audio_cache_test.dart
There are conflicts on writing to the same location of the temporary file path, when loading assets. This should be differentiated anyways as two individual AudioCaches should not share the same cache location.
Closes #1424 
#1424
> fix: Use unique tmp location for each AudioCache

- packages/audioplayers_darwin/ios/Classes/AudioContext.swift
Fixes the warning `'audioProcessing' was deprecated in iOS 10.0: No longer supported`.
Fixes #1402
Fixes #1722
> fix(ios): 'audioProcessing' deprecated in iOS 10

- .github/workflows/test.yml
On executing the windows tests, a virtual audio device is needed, which can only be installed with a certificate valid to a specific date. Recently the tests failed, as the date time was set before downloading and therefore threw a `NotTimeValid` error. This fixes that by downloading the source first, setting the date time and then installing it.
Occured in #925
> ci: Set system date time after downloading virtual audio device

- .github/workflows/test.yml
- packages/audioplayers/example/integration_test/lib_test.dart
Disabled flaky test for live streams on macos 13, as it's blocking the development but the test passes locally on macos 14.
> test: Disable flaky test for live streams on macos 13

- packages/audioplayers_linux/README.md
> docs: Add Fedora/RHEL Dependency instructions

- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/FocusManager.kt
- packages/audioplayers_android/android/src/main/kotlin/xyz/luan/audioplayers/player/WrappedPlayer.kt
Fixes https://github.com/bluefireteam/audioplayers/pull/1857#issuecomment-2574538819
> fix: Avoid multiple audioFocusRequest instances for focus changes

- packages/audioplayers/example/lib/tabs/audio_context.dart
- Only show audioContext option, if supported by the platform
- Automatically apply changes on select
> chore(example): Improved handling of platform context

- packages/audioplayers/example/integration_test/lib_test.dart
- packages/audioplayers_darwin/darwin/Classes/SwiftAudioplayersDarwinPlugin.swift
- packages/audioplayers_linux/linux/audioplayers_linux_plugin.cc
- packages/audioplayers_windows/windows/audioplayers_windows_plugin.cpp
Calling `setAudioContext` on the windows platform throws a `NotImplemented` error. `setAudioContext` is handled as a no-op in the global method call, but not in a method call for a single audio player. This PR simply adds that no-op (and log message) for a single audio player.
More context is here https://github.com/flame-engine/flame/issues/3498
Resolves https://github.com/flame-engine/flame/issues/3498
> fix: No-op on single player setAudioContext in desktop platforms

- .github/workflows/build-example.yml
- .github/workflows/pull-request.yml
- .github/workflows/test.yml
- packages/audioplayers/example/integration_test/platform_test.dart
- packages/audioplayers/lib/src/source.dart
> feat: Raise to Flutter 3.29.0

- packages/audioplayers/README.md
- packages/audioplayers_android/README.md
- packages/audioplayers_android_exo/README.md
- packages/audioplayers_darwin/README.md
- packages/audioplayers_linux/README.md
- packages/audioplayers_platform_interface/README.md
- packages/audioplayers_web/README.md
- packages/audioplayers_windows/README.md
Somehow got updated by GitHub.
Note: https://github.com/flame-engine/flame has the same problem.
> docs: Fix status badge

- .github/workflows/test.yml
- packages/audioplayers/example/pubspec.yaml
Now that audioplayers_android_exo is published, we can dynamically add the dependency (before melos is running) to test for both android plugin implementations.
> test: Reintroduce tests for audioplayers_android

- .github/workflows/test.yml
During publishing the package version dependencies are already raised to newer versions, which are not resolvable for `flutter pub add`. So we use path dependency. so common dependencies are in sync with melos relative dependencies.
See build failure of #1909
> ci: Use path dependency for audioplayers_android_exo tests

- packages/audioplayers/lib/src/audioplayer.dart
Added customizable timeout used for seeking and preparation of the player.
If the PR is a breaking change this should be indicated with suffix "!" 
(for example, `feat!:`, `fix!:`). See [Conventional Commit] for details. -->
Closes #1920
> feat: Customizable preparation and seeking timeout

- .github/workflows/build-example.yml
- .github/workflows/test.yml
- packages/audioplayers/example/pubspec.yaml
- packages/audioplayers/example/server/pubspec.yaml
- packages/audioplayers/pubspec.yaml
- packages/audioplayers_android/pubspec.yaml
- packages/audioplayers_android_exo/pubspec.yaml
- packages/audioplayers_darwin/pubspec.yaml
- packages/audioplayers_linux/pubspec.yaml
- packages/audioplayers_platform_interface/pubspec.yaml
- packages/audioplayers_web/pubspec.yaml
- packages/audioplayers_windows/pubspec.yaml
- pubspec.yaml
> chore: Allow Flutter versions '>3.x.x', test with 3.32.x
